import Foundation
import SwiftUI

enum AppLanguage: String, CaseIterable, Identifiable {
    case ru, en, kk

    var id: String { rawValue }

    var label: String {
        switch self {
        case .ru: return "Русский"
        case .en: return "English"
        case .kk: return "Қазақша"
        }
    }

    var flag: String {
        switch self {
        case .ru: return "🇷🇺"
        case .en: return "🇺🇸"
        case .kk: return "🇰🇿"
        }
    }
}

@MainActor
final class LocalizationService: ObservableObject {
    static let shared = LocalizationService()
    private static let languageOverrideKey = "x5.language"

    @Published private(set) var current: AppLanguage

    init() {
        // Read the user's REAL preferred language from iOS Settings — NOT Locale.current,
        // which depends on which languages the app advertises. preferredLanguages.first
        // returns e.g. "ru-KZ" / "kk-Cyrl-KZ" / "en-US" regardless of app localizations.
        self.current = Self.resolve()

        // React to system locale changes mid-session.
        NotificationCenter.default.addObserver(
            forName: NSLocale.currentLocaleDidChangeNotification,
            object: nil,
            queue: .main
        ) { [weak self] _ in
            Task { @MainActor in self?.refreshFromSystem() }
        }
    }

    private static func resolve() -> AppLanguage {
        if let saved = UserDefaults.standard.string(forKey: languageOverrideKey),
           let language = AppLanguage(rawValue: saved) {
            return language
        }

        let raw = Locale.preferredLanguages.first ?? "en"
        let code = raw.split(separator: "-").first.map(String.init)?.lowercased() ?? "en"
        switch code {
        case "ru": return .ru
        case "kk", "kz": return .kk
        default: return .en
        }
    }

    private func refreshFromSystem() {
        guard UserDefaults.standard.string(forKey: Self.languageOverrideKey) == nil else { return }
        let next = Self.resolve()
        if next != current { current = next }
    }

    func setLanguage(_ language: AppLanguage) {
        UserDefaults.standard.set(language.rawValue, forKey: Self.languageOverrideKey)
        if current != language { current = language }
    }

    func t(_ key: String) -> String {
        Self.dict[current]?[key] ?? Self.dict[.en]?[key] ?? key
    }
}

// MARK: - Translation dictionary

extension LocalizationService {
    static let dict: [AppLanguage: [String: String]] = [
        .ru: [
            // Common
            "btn_save": "Сохранить",
            "btn_cancel": "Отмена",
            "btn_back": "Назад",
            "btn_done": "Готово",
            "btn_delete": "Удалить",
            "btn_continue": "Продолжить",
            "btn_loading": "Загрузка…",
            "btn_retry": "Попробовать снова",
            "common_user": "Пользователь",
            "common_save": "Сохранить",
            "common_post": "Опубликовать",
            "common_load_failed": "Не удалось загрузить",
            "common_about": "О себе",
            "edit_specialist": "Специалист",
            "edit_show_in_hub": "Показывать в Hub",
            "edit_categories": "Категории",
            "edit_social": "Соцсети",
            "edit_about_section": "О себе",
            "courses_pro_chip": "Pro",
            "courses_draft": "ЧЕРНОВИК",
            "courses_unlock_pro": "Открыть с Pro",
            "courses_lessons_section": "УРОКИ",
            "courses_free_preview": "БЕСПЛАТНО",
            "courses_lessons_word": "уроков",
            "brand_voice_title": "Голос бренда",
            "brand_voice_sub": "Опционально — поможет сделать тексты в твоём стиле. Хранится только на этом устройстве.",
            "tool_in_dev": "В разработке — скоро",
            "tool_notify_me": "Сообщить, когда выйдет",
            "tool_will_let_you_know": "Сообщим, когда будет готово",
            "brand_name_field": "Название бренда",
            "brand_niche_field": "Ниша (например, спешелти-кофе)",
            "brand_audience_field": "Аудитория (например, городские профи)",
            "brand_words_field": "Слова бренда (через запятую)",
            "brand_reset": "Сбросить",
            "common_done": "Готово",
            "common_more": "Еще",
            "tool_desc_default": "Подробности скоро.",
            "tool_desc_photo": "Генерируй маркетинговые фото товаров и lifestyle-кадры по тексту. Подбирай ракурс, свет и стиль без студии.",
            "tool_desc_video_gen": "ИИ-видео (Kling 3.0). Преврати кадр или сценарий в короткий ролик для Reels, TikTok и Shorts.",
            "tool_desc_outfit_swap": "Меняй одежду на людях на любом фото, сохраняя силуэт и свет.",
            "tool_desc_lipsync": "Синхронизируй губы под любую дорожку. Озвучка и дубляж для Reels и рекламы.",
            "tool_desc_design": "Баннеры, сторис, рекламные сеты и питч-деки в твоём бренд-стиле.",
            "tool_desc_voice_tts": "Текст в речь с эмоциями. Разные голоса и языки для рекламы и обучения.",
            "tool_desc_whatsapp_bot": "Автоответчик для WhatsApp-лидов. Записывает, квалифицирует и распределяет 24/7.",
            "tool_desc_instagram": "Контент-план на 14 дней под твою нишу и тон.",
            "tool_desc_video_creative": "Сценарии Reels и TikTok по схеме hook → tension → CTA — готовы к съёмке.",
            "tool_desc_lawyer": "Договоры, NDA, акты и оферты под твой бизнес.",
            "tool_desc_academy": "Открой X5 Academy — вкладка «Курсы» внизу.",
            "tool_desc_crm": "Лёгкая CRM для соло-фаундеров и небольших агентств. Воронка, сделки, контакты.",
            "tool_desc_analytics": "Ежедневный KPI-дайджест: расход на рекламу, ROAS, топ-креативы, конверсия.",
            "tool_desc_captions": "Шаблоны подписей с учётом длины платформы. Этот инструмент уже работает — открой карточку.",
            "tool_desc_startup_chat": "Чат как GPT, но для запуска бизнеса: идея, ниша, оффер, упаковка, первые продажи и план действий.",
            "tool_desc_ai_influencer": "Собери виртуального инфлюенсера, который остаётся узнаваемым на фото и видео.",
            "tool_desc_edit_image": "Редактируй фото с ИИ: смена лиц, перевод света, ретушь, замена фона.",
            "tool_desc_vfx_library": "Кинематографичные переходы и VFX-библиотека. Добавь клип — выбери стиль.",
            "courses_load_failed": "Не удалось загрузить курсы",
            "history_empty_title": "Пока пусто",
            "history_empty_sub": "Здесь появятся сохранённые элементы.",
            "tool_status": "СТАТУС",
            "tool_coming_soon": "В разработке — скоро",
            "tool_what_it_does": "ЧТО БУДЕТ ДЕЛАТЬ",
            "task_section": "Задача",
            "task_budget_category": "Бюджет и категория",
            "task_budget": "Бюджет",
            "task_your_message": "Твоё сообщение",
            "task_response_footer": "Когда автор примет твой отклик, откроется приватный чат.",
            "task_send": "Отправить",
            "iap_signin_first": "Сначала войди в аккаунт",

            // Tabs
            "tab_home": "Главная",
            "tab_courses": "CourseUP",
            "tab_chats": "Чаты",
            "tab_hub": "Hub",
            "tab_profile": "Профиль",

            // Login
            "login_title": "Welcome to X5",
            "login_subtitle": "Маркетинг студия для креаторов.\nСоздавай, учись и нанимай — в одном приложении.",
            "login_signin": "Войти в X5",
            "login_signup": "Создать аккаунт",
            "login_continue_apple": "Continue with Apple",
            "login_continue_google": "Continue with Google",
            "login_continue_email": "Continue with Email",
            "login_email": "Email",
            "login_password": "Пароль",
            "login_create": "Создать аккаунт",
            "login_have_account": "Уже есть аккаунт? Войти",
            "login_new_here": "Новенький? Создать аккаунт",
            "login_invalid": "Неверный email или пароль.",
            "login_already": "Этот email уже зарегистрирован.",
            "login_password_short": "Пароль должен быть минимум 6 символов.",

            // Settings
            "settings_title": "Настройки",
            "settings_account": "Аккаунт",
            "settings_email": "Email",
            "settings_subscription": "Подписка",
            "settings_pro_active": "Pro · активна",
            "settings_free": "Бесплатно",
            "settings_language": "Язык",
            "settings_appearance": "Внешний вид",
            "settings_face_id": "Face ID",
            "settings_face_id_sub": "Защитить вход в приложение",
            "settings_public_profile": "Публичный профиль",
            "settings_public_profile_sub": "Показывать в Hub",
            "settings_notifications": "Уведомления",
            "settings_notifications_sub": "Открыть системные настройки",
            "settings_clear_cache": "Очистить кэш",
            "settings_cache": "Кэш",
            "settings_cache_sub": "Сколько занято и что удалить",
            "settings_promo": "Промо-уведомления",
            "settings_promo_sub": "Лёгкие напоминания каждые 5 минут",
            "cache_title": "Кэш",
            "cache_total": "Всего на диске",
            "cache_pick": "Что хранится",
            "cache_pick_hint": "Выбери категории, которые хочешь удалить. Без выбора — очистит всё.",
            "cache_empty": "Пусто",
            "cache_clear_all": "Очистить весь кэш",
            "cache_clear_selected": "Удалить выбранные",
            "cache_cat_avatars": "Аватары",
            "cache_cat_courses": "Обложки курсов",
            "cache_cat_portfolio": "Портфолио",
            "cache_cat_chat": "Медиа из чатов",
            "cache_cat_other": "Прочее",
            "settings_signout": "Выйти",
            "settings_legal": "Документы",
            "settings_privacy": "Политика конфиденциальности",
            "settings_terms": "Условия использования",
            "settings_support": "Связаться с поддержкой",
            "settings_danger": "Опасная зона",
            "settings_delete": "Удалить аккаунт",
            "settings_delete_footer": "Безвозвратно удалит ваш аккаунт и все связанные данные. Действие нельзя отменить.",
            "settings_delete_confirm": "Удалить аккаунт?",
            "settings_delete_confirm_msg": "Это действие необратимо. Будут удалены: профиль, история, кредиты, чаты, курсы и все ваши данные.",
            "settings_delete_sure": "Точно уверены?",
            "settings_delete_sure_msg": "После удаления восстановить аккаунт нельзя.",
            "settings_delete_forever": "Удалить навсегда",
            "settings_deleting": "Удаляем…",
            "settings_delete_failed": "Удаление не удалось",
            "settings_cache_cleared": "Кэш очищен",
            "settings_choose_language": "Язык приложения",

            // Hub
            "hub_title": "Hub",
            "hub_specialists": "Специалисты",
            "hub_tasks": "Задачи",
            "hub_post": "Пост",
            "hub_create_task": "Создать задачу",
            "hub_add_portfolio": "Добавить портфолио",
            "hub_become_specialist": "Стать специалистом",
            "hub_no_specialists": "Пока нет специалистов",
            "hub_no_specialists_sub": "Загляни позже — Hub наполняется.",
            "hub_no_tasks": "Нет открытых задач",
            "hub_no_tasks_sub": "Когда предприниматели добавят задачи — они появятся здесь.",
            "hub_send_message": "Написать сообщение",
            "hub_all": "Все",
            "hub_country_specialists": "Специалисты сейчас показываются для этой страны",
            "hub_country_orders": "Заказы сейчас показываются для этой страны",
            "hub_country_soon": "Другие страны позже",
            "country_kazakhstan": "Казахстан",
            "country_uzbekistan": "Узбекистан",
            "country_kyrgyzstan": "Кыргызстан",
            "country_uae": "ОАЭ",
            "country_turkey": "Турция",
            "country_usa": "США",

            // Chats
            "chats_title": "Чаты",
            "chats_archive": "Архив",
            "chats_unarchive": "Из архива",
            "chats_mute": "Без звука",
            "chats_unmute": "Со звуком",
            "chats_pin": "Закрепить",
            "chats_unpin": "Открепить",
            "chat_recording_hint": "Запись… отпусти чтобы отправить",
            "chat_voice_message": "Голосовое",
            "chat_block_title": "Заблокировать пользователя?",
            "chat_block_confirm": "Заблокировать",
            "chat_block_message": "Сообщения от этого пользователя больше не будут показываться.",
            "chat_open_profile": "Открыть профиль",
            "chat_report_user": "Пожаловаться",
            "chat_block_user": "Заблокировать",
            "common_cancel": "Отмена",
            "edit_hub_footer": "Включи «Показывать в Hub» — твой профиль появится в Hub, клиенты смогут написать в чат.",
            "edit_public_profile": "Публичный профиль для клиентов",
            "edit_name_placeholder": "Имя",
            "edit_nickname_placeholder": "Никнейм (a-z 0-9 _)",
            "edit_bio_placeholder": "Кратко о себе",
            "edit_social_footer": "Эти ссылки увидят клиенты в твоём профиле в Hub.",
            "edit_profile": "Профиль",
            "settings_language_footer": "Выбери язык приложения. Можно менять в любой момент.",
            "chats_search_placeholder": "Поиск в чате",
            "chats_date_today": "Сегодня",
            "chats_date_yesterday": "Вчера",
            "chats_preview_photo": "Фото",
            "chats_msg_sent": "Отправлено",
            "chats_msg_read": "Прочитано",
            "chats_msg_reply": "Ответить",
            "chats_msg_ask_startupchat": "Спросить StartupChat",
            "chats_msg_copy": "Копировать",
            "chats_msg_pin": "Закрепить",
            "chats_msg_unpin": "Открепить",
            "chats_msg_delete_for_me": "Удалить у меня",
            "chats_msg_forward": "Переслать",
            "chats_pinned_label": "Закреплено",
            "chats_delete": "Удалить",
            "chats_archive_empty_title": "Архив пуст",
            "chats_archive_empty_sub": "Свайпни чат влево чтоб скрыть его в архив",
            "chats_empty_title": "Пока нет переписок",
            "chats_empty_sub": "Открой Hub и напиши кому-нибудь.",
            "chats_no_messages": "(нет сообщений)",
            "chats_task": "Задача:",
            "chats_message_placeholder": "Сообщение…",
            "chats_send": "Отправить",
            "chats_view_profile": "тапни, чтобы открыть профиль",
            "chats_loading": "Загружаем чаты…",

            // Paywall (paywall_title is defined again below with "X5 Pro" — Swift dictionary literal dedup;
            // iOS 26.5 beta Swift runtime trap-s on duplicate keys, so we keep only one entry.)
            "paywall_desc": "Доступ ко всем AI-инструментам, премиум-курсам и безлимитным генерациям.",
            "paywall_active": "X5 Pro активна",
            "paywall_until": "До",
            "paywall_subscribe": "Подписаться",
            "paywall_loading": "Загружаем подписку…",
            "paywall_unavailable": "Подписка сейчас недоступна. Попробуйте позже.",
            "paywall_cancel_anytime": "Отменить можно в любой момент в настройках iOS",
            "paywall_privacy_link": "Политика конфиденциальности",
            "paywall_subscription_terms": "X5 Pro — автоматически продлеваемая ежемесячная подписка $9.99/мес. Оплата списывается с Apple ID при подтверждении покупки. Подписка продлевается автоматически, если не отменить её минимум за 24 часа до окончания периода. Управлять и отменить подписку можно в Настройках Apple ID. Любая неиспользованная часть бесплатного периода (если есть) сгорает при покупке подписки.",
            "paywall_restore": "Восстановить покупки",

            // Profile
            "profile_title": "Профиль",
            "profile_edit": "Редактировать профиль",
            "profile_credits": "Баланс",
            "profile_buy_credits": "Пополнить",
            "profile_upgrade": "Улучшить до Pro",
            "profile_get_verified": "Получить галочку",
            "profile_portfolio": "Портфолио",
            "profile_portfolio_empty": "Портфолио пустое",
            "profile_add_to_portfolio": "Добавить в портфолио",
            "profile_verified": "Проверенный",
            "common_share": "Поделиться",
            "profile_followers": "Подписчики",
            "profile_following": "Подписки",
            "profile_creations": "Работы",
            "profile_follow_action": "Подписаться",
            "profile_following_action": "Вы подписаны",
            "profile_pro_active": "X5 Pro активна",
            "profile_manage": "Управлять",
            "profile_renews": "Продление",
            "profile_month": "месяц",
            "profile_upgrade_sub": "1000 кредитов + все инструменты",
            "profile_become_specialist_title": "Стать специалистом",
            "profile_become_specialist_sub": "Включи публичный профиль: клиенты найдут тебя в Hub и напишут в чат.",
            "profile_verified_sub": "Синяя галочка рядом с именем: больше доверия и приоритет в Hub.",
            "profile_social": "Соцсети",
            "profile_specialist": "Специалист",
            "profile_on_hub": "В Hub",
            "profile_hidden": "Скрыт",
            "home_ai_tools": "AI-инструменты",
            "home_live_now": "Доступно сейчас",
            "home_generate": "Генерация",
            "home_media_photo_title": "Фото",
            "home_media_photo_subtitle": "Генерация и редактирование изображений",
            "home_media_logo_title": "Генерация лого",
            "home_media_logo_subtitle": "Логотип для бренда",
            "home_media_story_title": "Генерация сторис",
            "home_media_story_subtitle": "Вертикальный креатив 9:16",
            "home_media_post_title": "Генерация поста",
            "home_media_post_subtitle": "Пост для ленты",
            "home_media_instapack_title": "Упаковка Instagram",
            "home_media_instapack_subtitle": "Посты и сторис в одном стиле",
            "home_media_product_title": "Фото товара",
            "home_media_product_subtitle": "Кадр для рекламы",
            "home_media_packaging_title": "Дизайн упаковки",
            "home_media_packaging_subtitle": "Коробка, этикетка, мокап",
            "home_media_square_title": "Генерация 1:1",
            "home_media_square_subtitle": "Квадратный креатив для рекламы",
            "home_media_target_title": "Реклама для таргета",
            "home_media_target_subtitle": "Креатив для Instagram и TikTok",
            "home_media_youtube_title": "Обложка YouTube",
            "home_media_youtube_subtitle": "Кликабельная превью-картинка",
            "home_media_video_trends_title": "Тренды видео",
            "home_media_video_trends_subtitle": "Короткие ролики под Reels и TikTok",
            "home_media_fruit_video_title": "Фрукты видео",
            "home_media_fruit_video_subtitle": "Свежий продуктовый ролик за минуту",
            "home_media_ai_influencer_title": "AI-инфлюенсер",
            "home_media_ai_influencer_subtitle": "Выбери фон и создай персонажа",
            "home_media_custom_title": "Генерация изображения",
            "home_media_custom_subtitle": "Любой промпт, фото или идея",
            "home_media_video_title": "Генерация видео",
            "home_media_video_subtitle": "Kling AI: текст или фото в видео",
            "home_media_startup_chat_title": "Стартап чат",
            "home_media_startup_chat_subtitle": "ИИ-помощник для бизнеса",
            "gen_provider": "Провайдер",
            "gen_model": "Модель",
            "gen_settings": "Настройки",
            "gen_quantity": "Количество",
            "gen_size": "Размер",
            "gen_prompt": "Промпт",
            "gen_credits": "кредитов",
            "gen_balance": "Баланс",
            "gen_loading_balance": "Загружаем баланс",
            "gen_generating": "Генерируем...",
            "gen_need": "Нужно",
            "gen_generate": "Сгенерировать",
            "gen_prompt_required": "Напиши промпт или добавь фото",
            "gen_not_enough_credits": "Недостаточно кредитов.",
            "gen_open_viewer": "Открыть на весь экран",
            "gen_product_ad": "Реклама товара",
            "gen_clean_layout": "Чистый макет",
            "gen_is_generating": "генерирует",
            "gen_building": "Собираем",
            "gen_finishing": "Почти готово",
            "gen_result": "Результат",
            "gen_draw": "Рисовать",
            "gen_saved_photos": "Сохранено в Фото",
            "gen_gallery": "Галерея",
            "gen_gallery_empty_title": "Пока пусто",
            "gen_gallery_empty_subtitle": "Сгенерированные картинки будут сохраняться здесь.",
            "gen_saved_gallery": "Сохранено в галерею",
            "gen_save_failed": "Не удалось сохранить",
            "gen_action_download": "Скачать",
            "gen_action_share": "Поделиться",
            "gen_action_edit": "Редактировать",
            "gen_action_draw": "Рисовать",
            "gen_category_custom_title": "Генерация изображения",
            "gen_category_custom_subtitle": "Гибкая генерация по запросу",
            "gen_category_square_1_1_title": "Генерация 1:1",
            "gen_category_square_1_1_subtitle": "Квадратный рекламный креатив",
            "gen_category_logo_title": "Логотип",
            "gen_category_logo_subtitle": "Знак бренда",
            "gen_category_story_title": "Сторис",
            "gen_category_story_subtitle": "Вертикальный креатив",
            "gen_category_target_ad_title": "Реклама для таргета",
            "gen_category_target_ad_subtitle": "Креатив для Instagram и TikTok",
            "gen_category_youtube_cover_title": "Обложка YouTube",
            "gen_category_youtube_cover_subtitle": "Кликабельная превью-картинка",
            "gen_category_post_title": "Пост",
            "gen_category_post_subtitle": "Квадратный пост",
            "gen_category_insta_pack_title": "Упаковка Insta",
            "gen_category_insta_pack_subtitle": "Пост + сторис",
            "gen_category_product_title": "Товар",
            "gen_category_product_subtitle": "Рекламный кадр",
            "gen_category_packaging_title": "Упаковка",
            "gen_category_packaging_subtitle": "Коробка и этикетка",
            "home_tool_photo_title": "Создать картинку",
            "home_tool_photo_subtitle": "AI-генерация",
            "home_tool_captions_title": "Тексты",
            "home_tool_captions_subtitle": "Шаблоны подписей",
            "home_tool_academy_title": "Академия",
            "home_tool_academy_subtitle": "Курсы и обучение",

            // Notifications
            "notif_title": "Уведомления",
            "notif_empty": "Нет уведомлений",
            "notif_message_title": "Новое сообщение",
            "notif_like_title": "Новый лайк",
            "notif_follow_title": "Новый подписчик",
            "notif_followed_post_title": "Новый пост",

            // Verified
            "verified_title": "Получить галочку",
            "verified_subtitle": "Синяя ☑ рядом с твоим именем",
            "verified_benefit_1": "Приоритет в Hub — твои карточки выше",
            "verified_benefit_2": "Индикатор доверия для клиентов",
            "verified_benefit_3": "Знак того, что ты — настоящий специалист",
            "verified_subscribe": "Подписаться за 990 ₸/мес",
            "verified_active": "Галочка активна до",

            // App lock
            "app_lock_unlock_title": "Разблокируй X5",
            "app_lock_button": "Разблокировать",
            "app_lock_checking": "Проверяем…",
            "app_lock_unavailable": "Биометрия недоступна на устройстве. Отключи Face ID в настройках X5.",
            "app_lock_reason": "Доступ к X5",
            "app_lock_failed": "Не удалось разблокировать",
            "app_lock_passcode_fallback": "Введи код-пароль",

            // Notifications
            "notif_empty_desc": "Когда кто-то ответит на твою задачу, примет твоё предложение или напишет в чат — появится здесь.",

            // Hub report/block
            "hub_report_user": "Пожаловаться",
            "hub_block_user": "Заблокировать",
            "hub_block_author": "Заблокировать автора",
            "hub_block_user_title": "Заблокировать пользователя?",
            "hub_block_author_title": "Заблокировать автора?",
            "hub_block_user_message": "Контент этого пользователя больше не будет показываться.",
            "hub_block_author_message": "Задачи и сообщения этого автора больше не будут показываться.",
            "hub_open_profile": "Открыть профиль",

            // Hub task detail
            "hub_anonymous": "Анонимно",
            "hub_specialist": "Специалист",
            "hub_deadline": "Дедлайн",
            "hub_responses_label": "ОТКЛИКИ",
            "hub_no_responses": "Откликов пока нет.",
            "hub_author_notice": "Это твоя задача — отклики выше, можешь принять одного.",
            "hub_response_sent": "Твой отклик отправлен. Ждём, пока автор примет.",
            "hub_task_closed": "Задача закрыта для новых откликов.",
            "hub_respond_to_task": "Откликнуться",
            "hub_accepted": "ПРИНЯТ",

            // User profile
            "user_open": "Opening…",
            "user_send_message": "Написать сообщение",

            // Main view
            "main_target_length": "Целевая длина",
            "main_generate": "Сгенерировать",
            "main_short": "Коротко",
            "main_medium": "Средне",
            "main_long": "Длинно",

            // Onboarding
            "onb_title": "Расскажи о себе",
            "onb_subtitle": "Это поможет настроить опыт и то, что ты увидишь в Hub.",
            "onb_identity_section": "Профиль",
            "onb_identity_hint": "Имя и ник обязательны. Ник: минимум 3 символа, латиница, цифры или _.",
            "onb_name_required": "Введи настоящее имя. User и X5 нельзя оставить.",
            "onb_nickname_required": "Ник должен быть от 3 символов: a-z, 0-9 или _.",
            "onb_role_section": "Роль",
            "onb_role_required": "Выбери роль, чтобы продолжить.",
            "onb_session_expired": "Сессия устарела. Выйди и войди снова.",
            "onb_role_specialist": "Я специалист",
            "onb_role_specialist_sub": "Продаю свои навыки (маркетолог, дизайнер, разработчик, копирайтер и т.д.)",
            "onb_role_entrepreneur": "Я предприниматель",
            "onb_role_entrepreneur_sub": "Веду бизнес и хочу нанимать специалистов",
            "onb_role_creator": "Я креатор",
            "onb_role_creator_sub": "Создаю контент и хочу показывать портфолио, находить заказы и клиентов.",
            "onb_pick_categories": "Выбери до 8 категорий",
            "onb_bio_label": "Короткое био (по желанию)",
            "onb_bio_placeholder": "напр. 7 лет в performance-маркетинге для SaaS",
            "onb_entrepreneur_note": "Ты сможешь публиковать задачи в Hub и сразу писать специалистам.",
            "onb_continue": "Продолжить",
            "onb_saving": "Сохраняем…",
            "onb_save_failed": "Не удалось сохранить роль.",

            // Paywall extra
            "paywall_title": "X5 Pro",
            "paywall_feat_credits": "1000 кредитов при подписке",
            "paywall_feat_tools": "Все ИИ-инструменты (фото, видео, lipsync, дизайн)",
            "paywall_feat_courses": "Полная библиотека курсов",
            "paywall_feat_hub": "Найм проверенных маркетологов в Hub",
            "paywall_feat_support": "Приоритетная поддержка",
            "paywall_terms_link": "Условия использования (EULA)",
            "paywall_welcome_pro": "Добро пожаловать в Pro!",
            "paywall_credits_added": "1000 кредитов начислено на твой баланс.",
            "paywall_continue": "Продолжить",

            // Courses extra
            "courses_create_btn": "Создать",

            // Common
            "common_anonymous": "Анонимно",

            // IAP errors
            "iap_invalid_url": "Не удалось сформировать ссылку покупки.",

            // Settings extra
            "settings_manage_subscription": "Управление подпиской",
        ],
        .en: [
            "btn_save": "Save",
            "btn_cancel": "Cancel",
            "btn_back": "Back",
            "btn_done": "Done",
            "btn_delete": "Delete",
            "btn_continue": "Continue",
            "btn_loading": "Loading…",
            "btn_retry": "Try again",
            "common_user": "User",
            "common_save": "Save",
            "common_post": "Post",
            "common_load_failed": "Could not load",
            "common_about": "About",
            "edit_specialist": "Specialist",
            "edit_show_in_hub": "Show in Hub",
            "edit_categories": "Categories",
            "edit_social": "Social links",
            "edit_about_section": "About",
            "courses_pro_chip": "Pro",
            "courses_draft": "DRAFT",
            "courses_unlock_pro": "Unlock with Pro",
            "courses_lessons_section": "LESSONS",
            "courses_free_preview": "FREE PREVIEW",
            "courses_lessons_word": "lessons",
            "brand_voice_title": "Brand voice",
            "brand_voice_sub": "Optional — personalises your captions. Stored only on this device.",
            "tool_in_dev": "In development — coming soon",
            "tool_notify_me": "Notify me when ready",
            "tool_will_let_you_know": "We will let you know",
            "brand_name_field": "Brand name",
            "brand_niche_field": "Niche (e.g. third-wave coffee)",
            "brand_audience_field": "Audience (e.g. urban professionals)",
            "brand_words_field": "Brand words (comma-separated)",
            "brand_reset": "Reset",
            "common_done": "Done",
            "common_more": "More",
            "tool_desc_default": "More details soon.",
            "tool_desc_photo": "Generate marketing-grade product and lifestyle photos from a text prompt. Adjust angle, lighting and style without a studio.",
            "tool_desc_video_gen": "AI video generation (Kling 3.0). Turn a still or a script into a short clip ready for Reels, TikTok and Shorts.",
            "tool_desc_outfit_swap": "Swap outfits on people in any photo while preserving body shape and lighting.",
            "tool_desc_lipsync": "Sync lip movement to any audio track. Voice-overs and dubbing for Reels and ads.",
            "tool_desc_design": "Brand banners, story tiles, ad sets and pitch decks generated to your brand guide.",
            "tool_desc_voice_tts": "Text-to-speech with emotion control. Multiple voices and languages for ads and tutorials.",
            "tool_desc_whatsapp_bot": "Auto-responder for incoming WhatsApp leads. Books, qualifies and routes 24/7.",
            "tool_desc_instagram": "Content plan generator. Get a 14-day Instagram schedule tuned to your niche and tone.",
            "tool_desc_video_creative": "Reels and TikTok scripts with hook → tension → CTA structure, ready to film.",
            "tool_desc_lawyer": "Generate vetted contracts, NDAs, service acts and proposals tailored to your business.",
            "tool_desc_academy": "Open the X5 Academy. Tap the Courses tab in the navigation.",
            "tool_desc_crm": "Lightweight CRM for solo founders and small agencies. Pipeline, deals, contacts.",
            "tool_desc_analytics": "Daily KPI digest from your channels: ad spend, ROAS, top creatives, conversion.",
            "tool_desc_captions": "Caption templates with platform-aware length. This one is live today — tap the card to open.",
            "tool_desc_startup_chat": "A GPT-style chat for starting a business: idea, niche, offer, packaging, first sales, and action plan.",
            "tool_desc_ai_influencer": "Build a consistent virtual influencer character that stays on-model across photos and videos.",
            "tool_desc_edit_image": "Edit any photo with AI: face swap, relight, skin enhance, background change.",
            "tool_desc_vfx_library": "Cinematic transitions and VFX library. Drop a clip in, pick a style.",
            "courses_load_failed": "Could not load courses",
            "history_empty_title": "Nothing yet",
            "history_empty_sub": "Saved items will show up here.",
            "tool_status": "STATUS",
            "tool_coming_soon": "In development — coming soon",
            "tool_what_it_does": "WHAT IT WILL DO",
            "task_section": "Task",
            "task_budget_category": "Budget & category",
            "task_budget": "Budget",
            "task_your_message": "Your message",
            "task_response_footer": "When the author accepts your response, a private chat opens.",
            "task_send": "Send",
            "iap_signin_first": "Sign in first",

            "tab_home": "Home",
            "tab_courses": "CourseUP",
            "tab_chats": "Chats",
            "tab_hub": "Hub",
            "tab_profile": "Profile",

            "login_title": "Welcome to X5",
            "login_subtitle": "Marketing studio for creators.\nGenerate, learn, and hire — in one app.",
            "login_signin": "Sign in to X5",
            "login_signup": "Create your account",
            "login_continue_apple": "Continue with Apple",
            "login_continue_google": "Continue with Google",
            "login_continue_email": "Continue with Email",
            "login_email": "Email",
            "login_password": "Password",
            "login_create": "Create account",
            "login_have_account": "Already have an account? Sign in",
            "login_new_here": "New here? Create an account",
            "login_invalid": "Invalid email or password.",
            "login_already": "This email is already registered.",
            "login_password_short": "Password must be at least 6 characters.",

            "settings_title": "Settings",
            "settings_account": "Account",
            "settings_email": "Email",
            "settings_subscription": "Subscription",
            "settings_pro_active": "Pro · active",
            "settings_free": "Free",
            "settings_language": "Language",
            "settings_appearance": "Appearance",
            "settings_face_id": "Face ID",
            "settings_face_id_sub": "Protect app entry",
            "settings_public_profile": "Public profile",
            "settings_public_profile_sub": "Show me in Hub",
            "settings_notifications": "Notifications",
            "settings_notifications_sub": "Open system settings",
            "settings_clear_cache": "Clear cache",
            "settings_cache": "Cache",
            "settings_cache_sub": "See what's stored and clear it",
            "settings_promo": "Promo notifications",
            "settings_promo_sub": "Light reminders every 5 minutes",
            "cache_title": "Cache",
            "cache_total": "Total on disk",
            "cache_pick": "What's stored",
            "cache_pick_hint": "Pick categories to remove. Leave empty to wipe everything.",
            "cache_empty": "Empty",
            "cache_clear_all": "Clear all cache",
            "cache_clear_selected": "Delete selected",
            "cache_cat_avatars": "Avatars",
            "cache_cat_courses": "Course covers",
            "cache_cat_portfolio": "Portfolio",
            "cache_cat_chat": "Chat media",
            "cache_cat_other": "Other",
            "settings_signout": "Sign out",
            "settings_legal": "Legal",
            "settings_privacy": "Privacy Policy",
            "settings_terms": "Terms of Service",
            "settings_support": "Contact support",
            "settings_danger": "Danger zone",
            "settings_delete": "Delete account",
            "settings_delete_footer": "This will permanently delete your account and all associated data. This action cannot be undone.",
            "settings_delete_confirm": "Delete account?",
            "settings_delete_confirm_msg": "This will permanently remove your account and all associated data. You will not be able to recover it.",
            "settings_delete_sure": "Are you absolutely sure?",
            "settings_delete_sure_msg": "Once deleted, your account cannot be recovered.",
            "settings_delete_forever": "Delete forever",
            "settings_deleting": "Deleting…",
            "settings_delete_failed": "Delete failed",
            "settings_cache_cleared": "Cache cleared",
            "settings_choose_language": "App language",

            "hub_title": "Hub",
            "hub_specialists": "Specialists",
            "hub_tasks": "Tasks",
            "hub_post": "Post",
            "hub_create_task": "Create task",
            "hub_add_portfolio": "Add portfolio",
            "hub_become_specialist": "Become a specialist",
            "hub_no_specialists": "No specialists yet",
            "hub_no_specialists_sub": "Check back soon — Hub is filling up.",
            "hub_no_tasks": "No open tasks",
            "hub_no_tasks_sub": "When entrepreneurs post tasks, they'll appear here.",
            "hub_send_message": "Send message",
            "hub_all": "All",
            "hub_country_specialists": "Specialists are shown for this country now",
            "hub_country_orders": "Orders are shown for this country now",
            "hub_country_soon": "Other countries later",
            "country_kazakhstan": "Kazakhstan",
            "country_uzbekistan": "Uzbekistan",
            "country_kyrgyzstan": "Kyrgyzstan",
            "country_uae": "UAE",
            "country_turkey": "Turkey",
            "country_usa": "USA",

            "chats_title": "Chats",
            "chats_archive": "Archive",
            "chats_unarchive": "Unarchive",
            "chats_mute": "Mute",
            "chats_unmute": "Unmute",
            "chats_pin": "Pin",
            "chats_unpin": "Unpin",
            "chat_recording_hint": "Recording… release to send",
            "chat_voice_message": "Voice message",
            "chat_block_title": "Block this user?",
            "chat_block_confirm": "Block",
            "chat_block_message": "Messages from this user will no longer be shown.",
            "chat_open_profile": "Open profile",
            "chat_report_user": "Report",
            "chat_block_user": "Block",
            "common_cancel": "Cancel",
            "edit_hub_footer": "Toggle \"Show in Hub\" to make your profile visible to clients who can then start a chat.",
            "edit_public_profile": "Public profile for clients",
            "edit_name_placeholder": "Name",
            "edit_nickname_placeholder": "Username (a-z 0-9 _)",
            "edit_bio_placeholder": "A short bio",
            "edit_social_footer": "Clients will see these links on your Hub profile.",
            "edit_profile": "Profile",
            "settings_language_footer": "Choose the app language. You can change it anytime.",
            "chats_search_placeholder": "Search in chat",
            "chats_date_today": "Today",
            "chats_date_yesterday": "Yesterday",
            "chats_preview_photo": "Photo",
            "chats_msg_sent": "Sent",
            "chats_msg_read": "Read",
            "chats_msg_reply": "Reply",
            "chats_msg_ask_startupchat": "Ask StartupChat",
            "chats_msg_copy": "Copy",
            "chats_msg_pin": "Pin",
            "chats_msg_unpin": "Unpin",
            "chats_msg_delete_for_me": "Delete for me",
            "chats_msg_forward": "Forward",
            "chats_pinned_label": "Pinned",
            "chats_delete": "Delete",
            "chats_archive_empty_title": "Archive is empty",
            "chats_archive_empty_sub": "Swipe a chat left to move it here",
            "chats_empty_title": "No conversations yet",
            "chats_empty_sub": "Open Hub and reach out to someone.",
            "chats_no_messages": "(no messages)",
            "chats_task": "Task:",
            "chats_message_placeholder": "Message…",
            "chats_send": "Send",
            "chats_view_profile": "tap to view profile",
            "chats_loading": "Loading chats…",

            // paywall_title is defined again below with "X5 Pro" — kept single to avoid
            // Swift duplicate-key dictionary trap on iOS 26.5 beta.
            "paywall_desc": "Access all AI tools, premium courses, and unlimited generations.",
            "paywall_active": "X5 Pro Active",
            "paywall_until": "Until",
            "paywall_subscribe": "Subscribe",
            "paywall_loading": "Loading subscription…",
            "paywall_unavailable": "Subscription is not available right now. Please try again later.",
            "paywall_cancel_anytime": "Cancel anytime in iOS Settings",
            "paywall_privacy_link": "Privacy Policy",
            "paywall_subscription_terms": "X5 Pro is an auto-renewing monthly subscription at $9.99/month. Payment will be charged to your Apple ID at purchase confirmation. Subscription auto-renews unless cancelled at least 24 hours before the end of the current period. Manage or cancel anytime in your Apple ID settings. Any unused portion of a free trial period, if offered, will be forfeited when you purchase a subscription.",
            "paywall_restore": "Restore purchases",

            "profile_title": "Profile",
            "profile_edit": "Edit profile",
            "profile_credits": "Credits",
            "profile_buy_credits": "Top up",
            "profile_upgrade": "Upgrade to Pro",
            "profile_get_verified": "Get verified",
            "profile_portfolio": "Portfolio",
            "profile_portfolio_empty": "Portfolio is empty",
            "profile_add_to_portfolio": "Add to portfolio",
            "profile_verified": "Verified",
            "common_share": "Share",
            "profile_followers": "Followers",
            "profile_following": "Following",
            "profile_creations": "Creations",
            "profile_follow_action": "Follow",
            "profile_following_action": "Following",
            "profile_pro_active": "X5 Pro active",
            "profile_manage": "Manage",
            "profile_renews": "Renews",
            "profile_month": "month",
            "profile_upgrade_sub": "1000 credits + all tools",
            "profile_become_specialist_title": "Become a specialist",
            "profile_become_specialist_sub": "Turn on your public profile so clients can find you in Hub and message you.",
            "profile_verified_sub": "Blue check next to your name: more trust and priority in Hub.",
            "profile_social": "Social",
            "profile_specialist": "Specialist",
            "profile_on_hub": "On Hub",
            "profile_hidden": "Hidden",
            "home_ai_tools": "AI Tools",
            "home_live_now": "Live now",
            "home_generate": "Generate",
            "home_media_photo_title": "Photo",
            "home_media_photo_subtitle": "Generate and edit images",
            "home_media_logo_title": "Logo generation",
            "home_media_logo_subtitle": "Brand logo",
            "home_media_story_title": "Story generation",
            "home_media_story_subtitle": "Vertical creative 9:16",
            "home_media_post_title": "Post generation",
            "home_media_post_subtitle": "Feed post",
            "home_media_instapack_title": "Instagram pack",
            "home_media_instapack_subtitle": "Posts and stories in one style",
            "home_media_product_title": "Product photo",
            "home_media_product_subtitle": "Ad-ready shot",
            "home_media_packaging_title": "Packaging design",
            "home_media_packaging_subtitle": "Box, label, mockup",
            "home_media_square_title": "1:1 generation",
            "home_media_square_subtitle": "Square ad creative",
            "home_media_target_title": "Target ad creative",
            "home_media_target_subtitle": "Creative for Instagram and TikTok",
            "home_media_youtube_title": "YouTube thumbnail",
            "home_media_youtube_subtitle": "Clickable preview image",
            "home_media_video_trends_title": "Video trends",
            "home_media_video_trends_subtitle": "Short clips for Reels and TikTok",
            "home_media_fruit_video_title": "Fruit video",
            "home_media_fruit_video_subtitle": "Fresh product video in a minute",
            "home_media_ai_influencer_title": "AI influencer",
            "home_media_ai_influencer_subtitle": "Pick a background and create a character",
            "home_media_custom_title": "Image generation",
            "home_media_custom_subtitle": "Any prompt, photo or idea",
            "home_media_video_title": "Video generation",
            "home_media_video_subtitle": "Kling AI: text or image to video",
            "home_media_startup_chat_title": "Startup chat",
            "home_media_startup_chat_subtitle": "AI business assistant",
            "gen_provider": "Provider",
            "gen_model": "Model",
            "gen_settings": "Settings",
            "gen_quantity": "Images",
            "gen_size": "Size",
            "gen_prompt": "Prompt",
            "gen_credits": "credits",
            "gen_balance": "Balance",
            "gen_loading_balance": "Loading balance",
            "gen_generating": "Generating...",
            "gen_need": "Need",
            "gen_generate": "Generate",
            "gen_prompt_required": "Write a prompt or add a photo",
            "gen_not_enough_credits": "Not enough credits.",
            "gen_open_viewer": "Open viewer",
            "gen_product_ad": "Product ad",
            "gen_clean_layout": "Clean layout",
            "gen_is_generating": "is generating",
            "gen_building": "Building",
            "gen_finishing": "Almost ready",
            "gen_result": "Result",
            "gen_draw": "Draw",
            "gen_saved_photos": "Saved to Photos",
            "gen_gallery": "Gallery",
            "gen_gallery_empty_title": "Nothing yet",
            "gen_gallery_empty_subtitle": "Generated images will be saved here.",
            "gen_saved_gallery": "Saved to gallery",
            "gen_save_failed": "Could not save",
            "gen_action_download": "Download",
            "gen_action_share": "Share",
            "gen_action_edit": "Edit",
            "gen_action_draw": "Draw",
            "gen_category_custom_title": "Image generation",
            "gen_category_custom_subtitle": "Flexible prompt generation",
            "gen_category_square_1_1_title": "1:1 generation",
            "gen_category_square_1_1_subtitle": "Square ad creative",
            "gen_category_logo_title": "Logo",
            "gen_category_logo_subtitle": "Brand mark",
            "gen_category_story_title": "Story",
            "gen_category_story_subtitle": "Vertical creative",
            "gen_category_target_ad_title": "Target ad creative",
            "gen_category_target_ad_subtitle": "Creative for Instagram and TikTok",
            "gen_category_youtube_cover_title": "YouTube thumbnail",
            "gen_category_youtube_cover_subtitle": "Clickable preview image",
            "gen_category_post_title": "Post",
            "gen_category_post_subtitle": "Square feed post",
            "gen_category_insta_pack_title": "Insta Pack",
            "gen_category_insta_pack_subtitle": "Post + story mood",
            "gen_category_product_title": "Product",
            "gen_category_product_subtitle": "Ad-ready shot",
            "gen_category_packaging_title": "Packaging",
            "gen_category_packaging_subtitle": "Box and label",
            "home_tool_photo_title": "Create Image",
            "home_tool_photo_subtitle": "AI generation",
            "home_tool_captions_title": "Captions",
            "home_tool_captions_subtitle": "Caption templates",
            "home_tool_academy_title": "Academy",
            "home_tool_academy_subtitle": "Courses & training",

            "notif_title": "Notifications",
            "notif_empty": "No notifications",
            "notif_message_title": "New message",
            "notif_like_title": "New like",
            "notif_follow_title": "New follower",
            "notif_followed_post_title": "New post",

            "verified_title": "Get verified",
            "verified_subtitle": "A blue ☑ next to your name",
            "verified_benefit_1": "Priority in Hub — your cards rank higher",
            "verified_benefit_2": "Trust signal for clients",
            "verified_benefit_3": "Proof that you're a real specialist",
            "verified_subscribe": "Subscribe for $1.99/mo",
            "verified_active": "Verified until",

            // App lock
            "app_lock_unlock_title": "Unlock X5",
            "app_lock_button": "Unlock",
            "app_lock_checking": "Checking…",
            "app_lock_unavailable": "Biometry unavailable on this device. Disable Face ID in X5 settings.",
            "app_lock_reason": "Access X5",
            "app_lock_failed": "Could not unlock",
            "app_lock_passcode_fallback": "Enter passcode",

            // Notifications
            "notif_empty_desc": "When someone replies to your task, accepts your offer or sends a chat message, it will appear here.",

            // Hub report/block
            "hub_report_user": "Report",
            "hub_block_user": "Block",
            "hub_block_author": "Block author",
            "hub_block_user_title": "Block user?",
            "hub_block_author_title": "Block author?",
            "hub_block_user_message": "This user's content will no longer be shown.",
            "hub_block_author_message": "Tasks and messages from this author will no longer be shown.",
            "hub_open_profile": "Open profile",

            // Hub task detail
            "hub_anonymous": "Anonymous",
            "hub_specialist": "Specialist",
            "hub_deadline": "Deadline",
            "hub_responses_label": "RESPONSES",
            "hub_no_responses": "No responses yet.",
            "hub_author_notice": "This is your task — you'll see responses above and can accept one.",
            "hub_response_sent": "Your response is sent. Wait for the author to accept it.",
            "hub_task_closed": "This task is closed for new responses.",
            "hub_respond_to_task": "Respond to task",
            "hub_accepted": "ACCEPTED",

            // User profile
            "user_open": "Opening…",
            "user_send_message": "Send message",

            // Main view
            "main_target_length": "Target length",
            "main_generate": "Generate",
            "main_short": "Short",
            "main_medium": "Medium",
            "main_long": "Long",

            // Onboarding
            "onb_title": "Tell us who you are",
            "onb_subtitle": "This helps us tailor your experience and what you see in Hub.",
            "onb_identity_section": "Profile",
            "onb_identity_hint": "Name and username are required. Username: 3+ chars, a-z, 0-9, or _.",
            "onb_name_required": "Enter a real name. User and X5 cannot be kept.",
            "onb_nickname_required": "Username must be 3+ chars: a-z, 0-9, or _.",
            "onb_role_section": "Role",
            "onb_role_required": "Choose a role to continue.",
            "onb_session_expired": "Session expired. Sign out and sign in again.",
            "onb_role_specialist": "I'm a specialist",
            "onb_role_specialist_sub": "I sell my skills (marketer, designer, dev, copywriter, etc.)",
            "onb_role_entrepreneur": "I'm an entrepreneur",
            "onb_role_entrepreneur_sub": "I run a business and want to hire specialists",
            "onb_role_creator": "I'm a creator",
            "onb_role_creator_sub": "I create content and want to show my portfolio, get tasks, and find clients.",
            "onb_pick_categories": "Pick up to 8 categories",
            "onb_bio_label": "Short bio (optional)",
            "onb_bio_placeholder": "e.g. 7y in performance marketing for SaaS",
            "onb_entrepreneur_note": "You'll be able to post tasks in Hub and chat with specialists right after.",
            "onb_continue": "Continue",
            "onb_saving": "Saving…",
            "onb_save_failed": "Could not save your role.",

            // Paywall extra
            "paywall_title": "X5 Pro",
            "paywall_feat_credits": "1000 credits added on subscribe",
            "paywall_feat_tools": "All AI tools (image, video, lipsync, design)",
            "paywall_feat_courses": "Full courses library",
            "paywall_feat_hub": "Hire vetted marketers in Hub",
            "paywall_feat_support": "Priority support",
            "paywall_terms_link": "Terms of Use (EULA)",
            "paywall_welcome_pro": "Welcome to Pro!",
            "paywall_credits_added": "1000 credits have been added to your balance.",
            "paywall_continue": "Continue",

            // Courses extra
            "courses_create_btn": "Create",

            // Common
            "common_anonymous": "Anonymous",

            // IAP errors
            "iap_invalid_url": "Could not build purchase URL.",

            // Settings extra
            "settings_manage_subscription": "Manage subscription",
        ],
        .kk: [
            "btn_save": "Сақтау",
            "btn_cancel": "Болдырмау",
            "btn_back": "Артқа",
            "btn_done": "Дайын",
            "btn_delete": "Жою",
            "btn_continue": "Жалғастыру",
            "btn_loading": "Жүктелуде…",
            "btn_retry": "Қайта көру",
            "common_user": "Пайдаланушы",
            "common_save": "Сақтау",
            "common_post": "Жариялау",
            "common_load_failed": "Жүктеу мүмкін болмады",
            "common_about": "Өзім туралы",
            "edit_specialist": "Маман",
            "edit_show_in_hub": "Hub-та көрсету",
            "edit_categories": "Санаттар",
            "edit_social": "Әлеуметтік желілер",
            "edit_about_section": "Өзім туралы",
            "courses_pro_chip": "Pro",
            "courses_draft": "ҚАРАЛАМА",
            "courses_unlock_pro": "Pro-мен ашу",
            "courses_lessons_section": "САБАҚТАР",
            "courses_free_preview": "ТЕГІН",
            "courses_lessons_word": "сабақ",
            "brand_voice_title": "Бренд дауысы",
            "brand_voice_sub": "Қалауыңша — мәтіндер сенің стиліңде шығады. Тек осы құрылғыда сақталады.",
            "tool_in_dev": "Әзірленуде — жақында",
            "tool_notify_me": "Дайын болғанда хабарла",
            "tool_will_let_you_know": "Дайын болғанда хабарлаймыз",
            "brand_name_field": "Бренд атауы",
            "brand_niche_field": "Ниша (мысалы, спешелти-кофе)",
            "brand_audience_field": "Аудитория (мысалы, қалалық кәсіпқойлар)",
            "brand_words_field": "Бренд сөздері (үтір арқылы)",
            "brand_reset": "Қалпына келтіру",
            "common_done": "Дайын",
            "common_more": "Тағы",
            "tool_desc_default": "Толық ақпарат жақында.",
            "tool_desc_photo": "Мәтін бойынша маркетингтік өнім және lifestyle фотолар жасайды. Бұрышты, жарық пен стильді студиясыз баптайсың.",
            "tool_desc_video_gen": "ИИ-видео (Kling 3.0). Кадр немесе сценарий — Reels, TikTok және Shorts үшін қысқа ролик.",
            "tool_desc_outfit_swap": "Кез келген фотодағы адамның киімін ауыстыр — пішін мен жарық сақталады.",
            "tool_desc_lipsync": "Кез келген аудиоға ерін қимылын синхронда. Reels пен жарнамаға дубляж.",
            "tool_desc_design": "Сенің бренд-стиліңмен баннер, сторис, жарнама және питч-дек жасайды.",
            "tool_desc_voice_tts": "Эмоциясы бар мәтіннен сөйлеуге. Жарнама мен оқуға арналған әртүрлі дауыс пен тіл.",
            "tool_desc_whatsapp_bot": "WhatsApp лидтеріне авто-жауапшы. 24/7 жазады, квалификациялайды, бағыттайды.",
            "tool_desc_instagram": "14 күнге Instagram контент-жоспары — сенің нишаң мен үніңе сай.",
            "tool_desc_video_creative": "Reels және TikTok сценарийлері: hook → tension → CTA, түсіруге дайын.",
            "tool_desc_lawyer": "Сенің бизнесіңе бейімделген келісімшарт, NDA, акт және ұсыныстар.",
            "tool_desc_academy": "X5 Academy ашу. Төмендегі «Курстар» бөлімін бас.",
            "tool_desc_crm": "Соло-фаундерлер мен шағын агенттіктерге арналған жеңіл CRM. Шұңғыма, мәмілелер, контактілер.",
            "tool_desc_analytics": "Күн сайынғы KPI-дайджест: жарнама шығыны, ROAS, үздік креативтер, конверсия.",
            "tool_desc_captions": "Платформаға бейім ұзындықпен подпись шаблондары. Бұл құрал қазір жұмыс істейді — картаны бас.",
            "tool_desc_startup_chat": "Бизнесті бастауға арналған GPT стиліндегі чат: идея, ниша, оффер, қаптама, алғашқы сатылым және жоспар.",
            "tool_desc_ai_influencer": "Фото мен видеода біркелкі қалатын виртуал инфлюенсер құрастыр.",
            "tool_desc_edit_image": "ИИ-мен фотоны өңде: бет ауыстыру, жарық, тері ретушы, фон ауыстыру.",
            "tool_desc_vfx_library": "Кинематографиялық өтпелі эффекттер мен VFX кітапханасы. Клип қос — стильді таңда.",
            "courses_load_failed": "Курстар жүктелмеді",
            "history_empty_title": "Әлі бос",
            "history_empty_sub": "Сақталған заттар осында пайда болады.",
            "tool_status": "МӘРТЕБЕ",
            "tool_coming_soon": "Әзірленуде — жақында",
            "tool_what_it_does": "НЕ ІСТЕЙДІ",
            "task_section": "Тапсырма",
            "task_budget_category": "Бюджет және санат",
            "task_budget": "Бюджет",
            "task_your_message": "Хабарламаң",
            "task_response_footer": "Автор жауапты қабылдағанда жеке чат ашылады.",
            "task_send": "Жіберу",
            "iap_signin_first": "Алдымен кіріңіз",

            "tab_home": "Басты",
            "tab_courses": "CourseUP",
            "tab_chats": "Чаттар",
            "tab_hub": "Hub",
            "tab_profile": "Профиль",

            "login_title": "X5-ке қош келдің",
            "login_subtitle": "Креаторларға арналған маркетинг студиясы.\nГенерациялау, оқу, жалдау — бір қосымшада.",
            "login_signin": "X5-ке кіру",
            "login_signup": "Аккаунт құру",
            "login_continue_apple": "Apple арқылы кіру",
            "login_continue_google": "Google арқылы кіру",
            "login_continue_email": "Email арқылы кіру",
            "login_email": "Email",
            "login_password": "Құпиясөз",
            "login_create": "Аккаунт құру",
            "login_have_account": "Аккаунтың бар ма? Кіру",
            "login_new_here": "Жаңасың ба? Аккаунт құр",
            "login_invalid": "Қате email немесе құпиясөз.",
            "login_already": "Бұл email тіркелген.",
            "login_password_short": "Құпиясөз кемінде 6 таңба болуы керек.",

            "settings_title": "Баптаулар",
            "settings_account": "Аккаунт",
            "settings_email": "Email",
            "settings_subscription": "Жазылым",
            "settings_pro_active": "Pro · белсенді",
            "settings_free": "Тегін",
            "settings_language": "Тіл",
            "settings_appearance": "Көрініс",
            "settings_face_id": "Face ID",
            "settings_face_id_sub": "Қосымшаны қорғау",
            "settings_public_profile": "Публикалық профиль",
            "settings_public_profile_sub": "Hub-та көрсетілсін",
            "settings_notifications": "Хабарламалар",
            "settings_notifications_sub": "Жүйе баптауларын ашу",
            "settings_clear_cache": "Кэшті тазалау",
            "settings_cache": "Кэш",
            "settings_cache_sub": "Қанша орын алады және не өшіру",
            "settings_promo": "Промо хабарламалары",
            "settings_promo_sub": "Әр 5 минут сайын жеңіл еске салулар",
            "cache_title": "Кэш",
            "cache_total": "Дискіде барлығы",
            "cache_pick": "Не сақталған",
            "cache_pick_hint": "Өшіретін санаттарды таңда. Таңдалмаса — бәрін тазалайды.",
            "cache_empty": "Бос",
            "cache_clear_all": "Барлық кэшті тазалау",
            "cache_clear_selected": "Таңдалғанды өшіру",
            "cache_cat_avatars": "Аватарлар",
            "cache_cat_courses": "Курс мұқабалары",
            "cache_cat_portfolio": "Портфолио",
            "cache_cat_chat": "Чат медиасы",
            "cache_cat_other": "Басқа",
            "settings_signout": "Шығу",
            "settings_legal": "Құжаттар",
            "settings_privacy": "Құпиялылық саясаты",
            "settings_terms": "Қызмет шарттары",
            "settings_support": "Қолдауға хабарласу",
            "settings_danger": "Қауіпті аймақ",
            "settings_delete": "Аккаунтты жою",
            "settings_delete_footer": "Аккаунт пен барлық деректер біржола өшіріледі. Бұл әрекетті болдырмау мүмкін емес.",
            "settings_delete_confirm": "Аккаунтты жою керек пе?",
            "settings_delete_confirm_msg": "Бұл әрекет қайтымсыз. Профиль, тарих, кредиттер, чаттар, курстар — барлығы жойылады.",
            "settings_delete_sure": "Шынымен сенімдісің бе?",
            "settings_delete_sure_msg": "Жойылғаннан кейін аккаунтты қалпына келтіруге болмайды.",
            "settings_delete_forever": "Біржола жою",
            "settings_deleting": "Жойылуда…",
            "settings_delete_failed": "Жою сәтсіз",
            "settings_cache_cleared": "Кэш тазаланды",
            "settings_choose_language": "Қосымша тілі",

            "hub_title": "Hub",
            "hub_specialists": "Мамандар",
            "hub_tasks": "Тапсырмалар",
            "hub_post": "Жариялау",
            "hub_create_task": "Тапсырма жасау",
            "hub_add_portfolio": "Портфолио қосу",
            "hub_become_specialist": "Маман болу",
            "hub_no_specialists": "Әзірге маман жоқ",
            "hub_no_specialists_sub": "Кейінірек қара — Hub толып жатыр.",
            "hub_no_tasks": "Ашық тапсырма жоқ",
            "hub_no_tasks_sub": "Кәсіпкерлер тапсырма жариялағанда — осында пайда болады.",
            "hub_send_message": "Хабарлама жазу",
            "hub_all": "Барлығы",
            "hub_country_specialists": "Мамандар қазір осы ел үшін көрсетіледі",
            "hub_country_orders": "Тапсырыстар қазір осы ел үшін көрсетіледі",
            "hub_country_soon": "Басқа елдер кейінірек",
            "country_kazakhstan": "Қазақстан",
            "country_uzbekistan": "Өзбекстан",
            "country_kyrgyzstan": "Қырғызстан",
            "country_uae": "БАӘ",
            "country_turkey": "Түркия",
            "country_usa": "АҚШ",

            "chats_title": "Чаттар",
            "chats_archive": "Мұрағат",
            "chats_unarchive": "Мұрағаттан",
            "chats_mute": "Дыбыссыз",
            "chats_unmute": "Дыбыспен",
            "chats_pin": "Бекіту",
            "chats_unpin": "Босату",
            "chat_recording_hint": "Жазу… жіберу үшін босат",
            "chat_voice_message": "Дауыс",
            "chat_block_title": "Бұл пайдаланушыны бұғаттау?",
            "chat_block_confirm": "Бұғаттау",
            "chat_block_message": "Бұл пайдаланушының хабарламалары енді көрсетілмейді.",
            "chat_open_profile": "Профильді ашу",
            "chat_report_user": "Шағымдану",
            "chat_block_user": "Бұғаттау",
            "common_cancel": "Болдырмау",
            "edit_hub_footer": "«Hub-та көрсету» қосыңыз — профиліңіз Hub-та пайда болады, клиенттер чат жаза алады.",
            "edit_public_profile": "Клиенттерге арналған ашық профиль",
            "edit_name_placeholder": "Аты",
            "edit_nickname_placeholder": "Никнейм (a-z 0-9 _)",
            "edit_bio_placeholder": "Өзің туралы қысқаша",
            "edit_social_footer": "Бұл сілтемелерді клиенттер сіздің Hub профиліңізде көреді.",
            "edit_profile": "Профиль",
            "settings_language_footer": "Қолданба тілін таңдаңыз. Кез келген уақытта өзгертуге болады.",
            "chats_search_placeholder": "Чатта іздеу",
            "chats_date_today": "Бүгін",
            "chats_date_yesterday": "Кеше",
            "chats_preview_photo": "Фото",
            "chats_msg_sent": "Жіберілді",
            "chats_msg_read": "Оқылды",
            "chats_msg_reply": "Жауап беру",
            "chats_msg_ask_startupchat": "StartupChat-тан сұрау",
            "chats_msg_copy": "Көшіру",
            "chats_msg_pin": "Бекіту",
            "chats_msg_unpin": "Босату",
            "chats_msg_delete_for_me": "Менде өшіру",
            "chats_msg_forward": "Жіберу",
            "chats_pinned_label": "Бекітілген",
            "chats_delete": "Жою",
            "chats_archive_empty_title": "Мұрағат бос",
            "chats_archive_empty_sub": "Чатты солға сырғыт - мұрағатқа түседі",
            "chats_empty_title": "Әзірге чат жоқ",
            "chats_empty_sub": "Hub-ты ашып, біреуге жаз.",
            "chats_no_messages": "(хабарлама жоқ)",
            "chats_task": "Тапсырма:",
            "chats_message_placeholder": "Хабарлама…",
            "chats_send": "Жіберу",
            "chats_view_profile": "профильді ашу үшін басыңыз",
            "chats_loading": "Чаттар жүктелуде…",

            // paywall_title is defined again below with "X5 Pro" — kept single to avoid
            // Swift duplicate-key dictionary trap on iOS 26.5 beta.
            "paywall_desc": "Барлық AI құралдарға, премиум курстарға және шексіз генерацияларға қол жетімділік.",
            "paywall_active": "X5 Pro белсенді",
            "paywall_until": "Дейін",
            "paywall_subscribe": "Жазылу",
            "paywall_loading": "Жазылым жүктелуде…",
            "paywall_unavailable": "Жазылым қазір қол жетімсіз. Кейінірек көріңіз.",
            "paywall_cancel_anytime": "Кез келген уақытта iOS баптауларынан тоқтатуға болады",
            "paywall_privacy_link": "Құпиялылық саясаты",
            "paywall_subscription_terms": "X5 Pro — автоматты жаңартылатын айлық жазылым $9.99/ай. Төлем сатып алуды растаған кезде Apple ID-ге жазылады. Ағымдағы кезеңнің аяқталуына кемінде 24 сағат қалғанда тоқтатылмаса, жазылым автоматты түрде жаңарады. Жазылымды Apple ID параметрлерінде басқаруға және тоқтатуға болады.",
            "paywall_restore": "Сатып алуларды қалпына келтіру",

            "profile_title": "Профиль",
            "profile_edit": "Профильді өзгерту",
            "profile_credits": "Баланс",
            "profile_buy_credits": "Толтыру",
            "profile_upgrade": "Pro-ға жаңарту",
            "profile_get_verified": "Растау белгісін алу",
            "profile_portfolio": "Портфолио",
            "profile_portfolio_empty": "Портфолио бос",
            "profile_add_to_portfolio": "Портфолиоға қосу",
            "profile_verified": "Расталған",
            "common_share": "Бөлісу",
            "profile_followers": "Жазылушылар",
            "profile_following": "Жазылымдар",
            "profile_creations": "Жұмыстар",
            "profile_follow_action": "Жазылу",
            "profile_following_action": "Жазылған",
            "profile_pro_active": "X5 Pro белсенді",
            "profile_manage": "Басқару",
            "profile_renews": "Жаңарады",
            "profile_month": "ай",
            "profile_upgrade_sub": "1000 кредит + барлық құралдар",
            "profile_become_specialist_title": "Маман болу",
            "profile_become_specialist_sub": "Публичный профильді қос: клиенттер сені Hub-та тауып, чатқа жазады.",
            "profile_verified_sub": "Атыңның жанындағы көк белгі: көбірек сенім және Hub-та басымдық.",
            "profile_social": "Әлеуметтік желілер",
            "profile_specialist": "Маман",
            "profile_on_hub": "Hub-та",
            "profile_hidden": "Жасырын",
            "home_ai_tools": "AI-құралдар",
            "home_live_now": "Қазір қолжетімді",
            "home_generate": "Генерация",
            "home_media_photo_title": "Фото",
            "home_media_photo_subtitle": "Сурет жасау және өңдеу",
            "home_media_logo_title": "Лого генерациясы",
            "home_media_logo_subtitle": "Брендке арналған логотип",
            "home_media_story_title": "Сторис генерациясы",
            "home_media_story_subtitle": "Тік креатив 9:16",
            "home_media_post_title": "Пост генерациясы",
            "home_media_post_subtitle": "Лентаға арналған пост",
            "home_media_instapack_title": "Instagram пакет",
            "home_media_instapack_subtitle": "Пост пен сторис бір стильде",
            "home_media_product_title": "Тауар фотосы",
            "home_media_product_subtitle": "Жарнамаға дайын кадр",
            "home_media_packaging_title": "Қаптама дизайны",
            "home_media_packaging_subtitle": "Қорап, этикетка, мокап",
            "home_media_square_title": "1:1 генерация",
            "home_media_square_subtitle": "Жарнамаға квадрат креатив",
            "home_media_target_title": "Таргет жарнама",
            "home_media_target_subtitle": "Instagram және TikTok креативі",
            "home_media_youtube_title": "YouTube мұқаба",
            "home_media_youtube_subtitle": "Кликабельді превью сурет",
            "home_media_video_trends_title": "Видео трендтер",
            "home_media_video_trends_subtitle": "Reels және TikTok үшін қысқа роликтер",
            "home_media_fruit_video_title": "Жеміс видео",
            "home_media_fruit_video_subtitle": "Бір минутта өнім ролигі",
            "home_media_ai_influencer_title": "AI-инфлюенсер",
            "home_media_ai_influencer_subtitle": "Фон таңдап, персонаж жаса",
            "home_media_custom_title": "Сурет генерациясы",
            "home_media_custom_subtitle": "Кез келген промпт, фото немесе идея",
            "home_media_video_title": "Видео генерациясы",
            "home_media_video_subtitle": "Kling AI: мәтін немесе фотоны видеоға",
            "home_media_startup_chat_title": "Стартап чат",
            "home_media_startup_chat_subtitle": "Бизнеске арналған ИИ көмекші",
            "gen_provider": "Провайдер",
            "gen_model": "Модель",
            "gen_settings": "Баптаулар",
            "gen_quantity": "Саны",
            "gen_size": "Өлшем",
            "gen_prompt": "Промпт",
            "gen_credits": "кредит",
            "gen_balance": "Баланс",
            "gen_loading_balance": "Баланс жүктелуде",
            "gen_generating": "Генерация...",
            "gen_need": "Керек",
            "gen_generate": "Генерациялау",
            "gen_prompt_required": "Промпт жаз немесе фото қос",
            "gen_not_enough_credits": "Кредит жетпейді.",
            "gen_open_viewer": "Толық экранда ашу",
            "gen_product_ad": "Тауар жарнамасы",
            "gen_clean_layout": "Таза макет",
            "gen_is_generating": "генерациялайды",
            "gen_building": "Жасалуда",
            "gen_finishing": "Дайын болып қалды",
            "gen_result": "Нәтиже",
            "gen_draw": "Салу",
            "gen_saved_photos": "Фотоға сақталды",
            "gen_gallery": "Галерея",
            "gen_gallery_empty_title": "Әзірге бос",
            "gen_gallery_empty_subtitle": "Генерацияланған суреттер осында сақталады.",
            "gen_saved_gallery": "Галереяға сақталды",
            "gen_save_failed": "Сақтау мүмкін болмады",
            "gen_action_download": "Жүктеу",
            "gen_action_share": "Бөлісу",
            "gen_action_edit": "Өңдеу",
            "gen_action_draw": "Салу",
            "gen_category_custom_title": "Сурет генерациясы",
            "gen_category_custom_subtitle": "Промпт бойынша икемді генерация",
            "gen_category_square_1_1_title": "1:1 генерация",
            "gen_category_square_1_1_subtitle": "Квадрат жарнама креативі",
            "gen_category_logo_title": "Логотип",
            "gen_category_logo_subtitle": "Бренд белгісі",
            "gen_category_story_title": "Сторис",
            "gen_category_story_subtitle": "Вертикалды креатив",
            "gen_category_target_ad_title": "Таргет жарнама",
            "gen_category_target_ad_subtitle": "Instagram және TikTok креативі",
            "gen_category_youtube_cover_title": "YouTube мұқаба",
            "gen_category_youtube_cover_subtitle": "Кликабельді превью сурет",
            "gen_category_post_title": "Пост",
            "gen_category_post_subtitle": "Квадрат пост",
            "gen_category_insta_pack_title": "Insta пакет",
            "gen_category_insta_pack_subtitle": "Пост + сторис",
            "gen_category_product_title": "Тауар",
            "gen_category_product_subtitle": "Жарнамалық кадр",
            "gen_category_packaging_title": "Қаптама",
            "gen_category_packaging_subtitle": "Қорап және этикетка",
            "home_tool_photo_title": "Сурет жасау",
            "home_tool_photo_subtitle": "AI-генерация",
            "home_tool_captions_title": "Мәтіндер",
            "home_tool_captions_subtitle": "Caption шаблондары",
            "home_tool_academy_title": "Академия",
            "home_tool_academy_subtitle": "Курстар және оқу",

            "notif_title": "Хабарламалар",
            "notif_empty": "Хабарлама жоқ",
            "notif_message_title": "Жаңа хабарлама",
            "notif_like_title": "Жаңа лайк",
            "notif_follow_title": "Жаңа жазылушы",
            "notif_followed_post_title": "Жаңа пост",

            "verified_title": "Растау белгісін алу",
            "verified_subtitle": "Атың жанындағы көк ☑",
            "verified_benefit_1": "Hub-та басымдылық — карточкаң жоғары тұрады",
            "verified_benefit_2": "Клиенттер үшін сенім белгісі",
            "verified_benefit_3": "Сен нағыз маман екеніңнің дәлелі",
            "verified_subscribe": "990 ₸/айға жазылу",
            "verified_active": "Дейін расталған",

            // App lock
            "app_lock_unlock_title": "X5-ті ашу",
            "app_lock_button": "Ашу",
            "app_lock_checking": "Тексеру…",
            "app_lock_unavailable": "Биометрия қол жетімсіз. X5 параметрлерінде Face ID өшіріңіз.",
            "app_lock_reason": "X5-ке кіру",
            "app_lock_failed": "Аша алмадық",
            "app_lock_passcode_fallback": "Құпиясөзді еңгіз",

            // Notifications
            "notif_empty_desc": "Біреу тапсырмаңа жауап берсе, ұсынысыңды қабылдаса немесе чатқа жазса — осында пайда болады.",

            // Hub report/block
            "hub_report_user": "Шағымдану",
            "hub_block_user": "Блоктау",
            "hub_block_author": "Авторды блоктау",
            "hub_block_user_title": "Қолданушыны блоктау?",
            "hub_block_author_title": "Авторды блоктау?",
            "hub_block_user_message": "Бұл қолданушының контенті бұдан былай көрсетілмейді.",
            "hub_block_author_message": "Бұл автордың тапсырмалары мен хабарлары бұдан былай көрсетілмейді.",
            "hub_open_profile": "Профильді ашу",

            // Hub task detail
            "hub_anonymous": "Анонимді",
            "hub_specialist": "Маман",
            "hub_deadline": "Мерзімі",
            "hub_responses_label": "ЖАУАПТАР",
            "hub_no_responses": "Әлі жауап жоқ.",
            "hub_author_notice": "Бұл — сенің тапсырмаң. Жауаптар жоғарыда, біреуін қабылдай аласың.",
            "hub_response_sent": "Жауабың жіберілді. Автор қабылдағанша күт.",
            "hub_task_closed": "Бұл тапсырма жаңа жауаптар үшін жабық.",
            "hub_respond_to_task": "Жауап беру",
            "hub_accepted": "ҚАБЫЛДАНДЫ",

            // User profile
            "user_open": "Ашу…",
            "user_send_message": "Хабарлама жазу",

            // Main view
            "main_target_length": "Қажетті ұзындық",
            "main_generate": "Генерациялау",
            "main_short": "Қысқа",
            "main_medium": "Орташа",
            "main_long": "Ұзақ",

            // Onboarding
            "onb_title": "Өзің туралы айтып бер",
            "onb_subtitle": "Бұл тәжірибеңді және Hub-та көретін нәрсені баптауға көмектеседі.",
            "onb_identity_section": "Профиль",
            "onb_identity_hint": "Аты мен никнейм міндетті. Никнейм: кемі 3 таңба, a-z, 0-9 немесе _.",
            "onb_name_required": "Нақты атыңды енгіз. User және X5 қалдыруға болмайды.",
            "onb_nickname_required": "Никнейм кемі 3 таңба болуы керек: a-z, 0-9 немесе _.",
            "onb_role_section": "Рөл",
            "onb_role_required": "Жалғастыру үшін рөлді таңда.",
            "onb_session_expired": "Сессия ескірді. Шығып, қайта кір.",
            "onb_role_specialist": "Мен маманмын",
            "onb_role_specialist_sub": "Дағдыларымды сатамын (маркетолог, дизайнер, әзірлеуші, копирайтер және т.б.)",
            "onb_role_entrepreneur": "Мен кәсіпкермін",
            "onb_role_entrepreneur_sub": "Бизнес жүргіземін, мамандарды жалдағым келеді",
            "onb_role_creator": "Мен креатормын",
            "onb_role_creator_sub": "Контент жасап, портфолиомды көрсетіп, тапсырыс пен клиент тапқым келеді.",
            "onb_pick_categories": "8-ге дейін санат таңда",
            "onb_bio_label": "Қысқа био (қалауыңша)",
            "onb_bio_placeholder": "мысалы, SaaS-ке 7 жыл performance-маркетинг",
            "onb_entrepreneur_note": "Hub-та тапсырмалар жариялап, мамандармен бірден чатта сөйлесе аласың.",
            "onb_continue": "Жалғастыру",
            "onb_saving": "Сақтау…",
            "onb_save_failed": "Рөлді сақтау сәтсіз.",

            // Paywall extra
            "paywall_title": "X5 Pro",
            "paywall_feat_credits": "Жазылған кезде 1000 кредит қосылады",
            "paywall_feat_tools": "Барлық ИИ-құралдар (фото, видео, lipsync, дизайн)",
            "paywall_feat_courses": "Курстар кітапханасы толық",
            "paywall_feat_hub": "Hub-та расталған маркетологтарды жалдау",
            "paywall_feat_support": "Басым қолдау",
            "paywall_terms_link": "Қолдану шарттары (EULA)",
            "paywall_welcome_pro": "Pro-ға қош келдің!",
            "paywall_credits_added": "Балансыңа 1000 кредит қосылды.",
            "paywall_continue": "Жалғастыру",

            // Courses extra
            "courses_create_btn": "Жасау",

            // Common
            "common_anonymous": "Анонимді",

            // IAP errors
            "iap_invalid_url": "Сатып алу сілтемесін жасай алмадық.",

            // Settings extra
            "settings_manage_subscription": "Жазылымды басқару",
        ]
    ]
}
