import Foundation
import SwiftUI

enum AppLanguage: String, CaseIterable, Identifiable {
    case ru, en, kk

    var id: String { rawValue }

    var label: String {
        switch self {
        case .ru: return "Русский"
        case .en: return "English"
        case .kk: return "Қазақша"
        }
    }

    var flag: String {
        switch self {
        case .ru: return "🇷🇺"
        case .en: return "🇺🇸"
        case .kk: return "🇰🇿"
        }
    }
}

@MainActor
final class LocalizationService: ObservableObject {
    static let shared = LocalizationService()

    @Published private(set) var current: AppLanguage

    init() {
        // Read the user's REAL preferred language from iOS Settings — NOT Locale.current,
        // which depends on which languages the app advertises. preferredLanguages.first
        // returns e.g. "ru-KZ" / "kk-Cyrl-KZ" / "en-US" regardless of app localizations.
        self.current = Self.resolve()

        // React to system locale changes mid-session.
        NotificationCenter.default.addObserver(
            forName: NSLocale.currentLocaleDidChangeNotification,
            object: nil,
            queue: .main
        ) { [weak self] _ in
            Task { @MainActor in self?.refreshFromSystem() }
        }
    }

    private static func resolve() -> AppLanguage {
        let raw = Locale.preferredLanguages.first ?? "en"
        let code = raw.split(separator: "-").first.map(String.init)?.lowercased() ?? "en"
        switch code {
        case "ru": return .ru
        case "kk", "kz": return .kk
        default: return .en
        }
    }

    private func refreshFromSystem() {
        let next = Self.resolve()
        if next != current { current = next }
    }

    func t(_ key: String) -> String {
        Self.dict[current]?[key] ?? Self.dict[.en]?[key] ?? key
    }
}

// MARK: - Translation dictionary

extension LocalizationService {
    static let dict: [AppLanguage: [String: String]] = [
        .ru: [
            // Common
            "btn_save": "Сохранить",
            "btn_cancel": "Отмена",
            "btn_back": "Назад",
            "btn_done": "Готово",
            "btn_delete": "Удалить",
            "btn_continue": "Продолжить",
            "btn_loading": "Загрузка…",
            "btn_retry": "Попробовать снова",
            "common_user": "Пользователь",
            "common_save": "Сохранить",
            "common_post": "Опубликовать",
            "common_load_failed": "Не удалось загрузить",
            "common_about": "О себе",
            "edit_specialist": "Специалист",
            "edit_show_in_hub": "Показывать в Hub",
            "edit_categories": "Категории",
            "edit_social": "Соцсети",
            "edit_about_section": "О себе",
            "courses_pro_chip": "Pro",
            "courses_draft": "ЧЕРНОВИК",
            "courses_unlock_pro": "Открыть с Pro",
            "courses_lessons_section": "УРОКИ",
            "courses_free_preview": "БЕСПЛАТНО",
            "courses_lessons_word": "уроков",
            "brand_voice_title": "Голос бренда",
            "brand_voice_sub": "Опционально — поможет сделать тексты в твоём стиле. Хранится только на этом устройстве.",
            "tool_in_dev": "В разработке — скоро",
            "tool_notify_me": "Сообщить, когда выйдет",
            "tool_will_let_you_know": "Сообщим, когда будет готово",
            "brand_name_field": "Название бренда",
            "brand_niche_field": "Ниша (например, спешелти-кофе)",
            "brand_audience_field": "Аудитория (например, городские профи)",
            "brand_words_field": "Слова бренда (через запятую)",
            "brand_reset": "Сбросить",
            "common_done": "Готово",
            "tool_desc_default": "Подробности скоро.",
            "tool_desc_photo": "Генерируй маркетинговые фото товаров и lifestyle-кадры по тексту. Подбирай ракурс, свет и стиль без студии.",
            "tool_desc_video_gen": "ИИ-видео (Kling 3.0). Преврати кадр или сценарий в короткий ролик для Reels, TikTok и Shorts.",
            "tool_desc_outfit_swap": "Меняй одежду на людях на любом фото, сохраняя силуэт и свет.",
            "tool_desc_lipsync": "Синхронизируй губы под любую дорожку. Озвучка и дубляж для Reels и рекламы.",
            "tool_desc_design": "Баннеры, сторис, рекламные сеты и питч-деки в твоём бренд-стиле.",
            "tool_desc_voice_tts": "Текст в речь с эмоциями. Разные голоса и языки для рекламы и обучения.",
            "tool_desc_whatsapp_bot": "Автоответчик для WhatsApp-лидов. Записывает, квалифицирует и распределяет 24/7.",
            "tool_desc_instagram": "Контент-план на 14 дней под твою нишу и тон.",
            "tool_desc_video_creative": "Сценарии Reels и TikTok по схеме hook → tension → CTA — готовы к съёмке.",
            "tool_desc_lawyer": "Договоры, NDA, акты и оферты под твой бизнес.",
            "tool_desc_academy": "Открой X5 Academy — вкладка «Курсы» внизу.",
            "tool_desc_crm": "Лёгкая CRM для соло-фаундеров и небольших агентств. Воронка, сделки, контакты.",
            "tool_desc_analytics": "Ежедневный KPI-дайджест: расход на рекламу, ROAS, топ-креативы, конверсия.",
            "tool_desc_captions": "Шаблоны подписей с учётом длины платформы. Этот инструмент уже работает — открой карточку.",
            "tool_desc_ai_influencer": "Собери виртуального инфлюенсера, который остаётся узнаваемым на фото и видео.",
            "tool_desc_edit_image": "Редактируй фото с ИИ: смена лиц, перевод света, ретушь, замена фона.",
            "tool_desc_vfx_library": "Кинематографичные переходы и VFX-библиотека. Добавь клип — выбери стиль.",
            "courses_load_failed": "Не удалось загрузить курсы",
            "history_empty_title": "Пока пусто",
            "history_empty_sub": "Здесь появятся сохранённые элементы.",
            "tool_status": "СТАТУС",
            "tool_coming_soon": "В разработке — скоро",
            "tool_what_it_does": "ЧТО БУДЕТ ДЕЛАТЬ",
            "task_section": "Задача",
            "task_budget_category": "Бюджет и категория",
            "task_budget": "Бюджет",
            "task_your_message": "Твоё сообщение",
            "task_response_footer": "Когда автор примет твой отклик, откроется приватный чат.",
            "task_send": "Отправить",
            "iap_signin_first": "Сначала войди в аккаунт",

            // Tabs
            "tab_home": "Главная",
            "tab_courses": "Курсы",
            "tab_chats": "Чаты",
            "tab_hub": "Hub",
            "tab_profile": "Профиль",

            // Login
            "login_title": "Welcome to X5",
            "login_subtitle": "Маркетинг студия для креаторов.\nСоздавай, учись и нанимай — в одном приложении.",
            "login_signin": "Войти в X5",
            "login_signup": "Создать аккаунт",
            "login_continue_apple": "Continue with Apple",
            "login_continue_google": "Continue with Google",
            "login_continue_email": "Continue with Email",
            "login_email": "Email",
            "login_password": "Пароль",
            "login_create": "Создать аккаунт",
            "login_have_account": "Уже есть аккаунт? Войти",
            "login_new_here": "Новенький? Создать аккаунт",
            "login_invalid": "Неверный email или пароль.",
            "login_already": "Этот email уже зарегистрирован.",
            "login_password_short": "Пароль должен быть минимум 6 символов.",

            // Settings
            "settings_title": "Настройки",
            "settings_account": "Аккаунт",
            "settings_email": "Email",
            "settings_subscription": "Подписка",
            "settings_pro_active": "Pro · активна",
            "settings_free": "Бесплатно",
            "settings_language": "Язык",
            "settings_appearance": "Внешний вид",
            "settings_face_id": "Face ID",
            "settings_face_id_sub": "Защитить вход в приложение",
            "settings_public_profile": "Публичный профиль",
            "settings_public_profile_sub": "Показывать в Hub",
            "settings_notifications": "Уведомления",
            "settings_notifications_sub": "Открыть системные настройки",
            "settings_clear_cache": "Очистить кэш",
            "settings_cache": "Кэш",
            "settings_cache_sub": "Сколько занято и что удалить",
            "settings_promo": "Промо-уведомления",
            "settings_promo_sub": "Лёгкие напоминания каждые 5 минут",
            "cache_title": "Кэш",
            "cache_total": "Всего на диске",
            "cache_pick": "Что хранится",
            "cache_pick_hint": "Выбери категории, которые хочешь удалить. Без выбора — очистит всё.",
            "cache_empty": "Пусто",
            "cache_clear_all": "Очистить весь кэш",
            "cache_clear_selected": "Удалить выбранные",
            "cache_cat_avatars": "Аватары",
            "cache_cat_courses": "Обложки курсов",
            "cache_cat_portfolio": "Портфолио",
            "cache_cat_chat": "Медиа из чатов",
            "cache_cat_other": "Прочее",
            "settings_signout": "Выйти",
            "settings_legal": "Документы",
            "settings_privacy": "Политика конфиденциальности",
            "settings_terms": "Условия использования",
            "settings_support": "Связаться с поддержкой",
            "settings_danger": "Опасная зона",
            "settings_delete": "Удалить аккаунт",
            "settings_delete_footer": "Безвозвратно удалит ваш аккаунт и все связанные данные. Действие нельзя отменить.",
            "settings_delete_confirm": "Удалить аккаунт?",
            "settings_delete_confirm_msg": "Это действие необратимо. Будут удалены: профиль, история, кредиты, чаты, курсы и все ваши данные.",
            "settings_delete_sure": "Точно уверены?",
            "settings_delete_sure_msg": "После удаления восстановить аккаунт нельзя.",
            "settings_delete_forever": "Удалить навсегда",
            "settings_deleting": "Удаляем…",
            "settings_delete_failed": "Удаление не удалось",
            "settings_cache_cleared": "Кэш очищен",
            "settings_choose_language": "Язык приложения",

            // Hub
            "hub_title": "Hub",
            "hub_specialists": "Специалисты",
            "hub_tasks": "Задачи",
            "hub_post": "Пост",
            "hub_become_specialist": "Стать специалистом",
            "hub_no_specialists": "Пока нет специалистов",
            "hub_no_specialists_sub": "Загляни позже — Hub наполняется.",
            "hub_no_tasks": "Нет открытых задач",
            "hub_no_tasks_sub": "Когда предприниматели добавят задачи — они появятся здесь.",
            "hub_send_message": "Написать сообщение",
            "hub_all": "Все",

            // Chats
            "chats_title": "Чаты",
            "chats_archive": "Архив",
            "chats_unarchive": "Из архива",
            "chats_mute": "Без звука",
            "chats_unmute": "Со звуком",
            "chats_pin": "Закрепить",
            "chats_unpin": "Открепить",
            "chat_recording_hint": "Запись… отпусти чтобы отправить",
            "chat_voice_message": "Голосовое",
            "chat_block_title": "Заблокировать пользователя?",
            "chat_block_confirm": "Заблокировать",
            "chat_block_message": "Сообщения от этого пользователя больше не будут показываться.",
            "chat_open_profile": "Открыть профиль",
            "chat_report_user": "Пожаловаться",
            "chat_block_user": "Заблокировать",
            "common_cancel": "Отмена",
            "edit_hub_footer": "Включи «Показывать в Hub» — твой профиль появится в Hub, клиенты смогут написать в чат.",
            "edit_public_profile": "Публичный профиль для клиентов",
            "edit_name_placeholder": "Имя",
            "edit_nickname_placeholder": "Никнейм (a-z 0-9 _)",
            "edit_bio_placeholder": "Кратко о себе",
            "edit_social_footer": "Эти ссылки увидят клиенты в твоём профиле в Hub.",
            "edit_profile": "Профиль",
            "settings_language_footer": "Язык приложения берётся из языка iPhone. Чтобы сменить — Настройки iOS → X5 → Язык.",
            "settings_lang_from_system": "из системы",
            "portfolio_title": "Портфолио",
            "portfolio_empty_self": "Загрузи свои работы",
            "portfolio_empty_other": "Портфолио пустое",
            "portfolio_delete_title": "Удалить из портфолио?",
            "portfolio_pick_photo": "Выбрать фото",
            "portfolio_description_section": "Описание",
            "portfolio_title_optional": "Название (опц.)",
            "portfolio_desc_optional": "Кейс / описание (опц.)",
            "portfolio_add_title": "Добавить в портфолио",
            "portfolio_save_failed": "Не удалось сохранить. Попробуй ещё раз.",
            "common_add": "Добавить",
            "common_delete": "Удалить",
            "profile_become_specialist": "Стать специалистом",
            "profile_become_specialist_sub": "Включи публичный профиль — клиенты найдут тебя в Hub и напишут в чат",
            "profile_get_verified": "Получить галочку",
            "profile_get_verified_sub": "Синяя ☑ рядом с именем — больше доверия и приоритет в Hub",
            "hub_chat_failed": "Чат не открылся",
            "hub_chat_failed_retry": "Не удалось открыть чат. Попробуй ещё раз.",
            "verified_activated_message": "Синяя галочка теперь рядом с твоим именем. Списано %d кредитов.",
            "verified_cost_label": "%d кредитов / 30 дней",
            "verified_balance": "Твой баланс: %d",
            "verified_activating": "Списываем…",
            "verified_activate_for": "Активировать за %d кредитов",
            "verified_buy_pro_to_get_credits": "Купить Pro и получить кредиты",
            "verified_pro_credits_hint": "Pro = +1000 кредитов сразу",
            "verified_activate_failed": "Не удалось активировать. Попробуй позже.",
            "iap_not_enough_credits": "Не хватает кредитов: нужно %d, у тебя %d. Купи Pro — получишь 1000 кредитов.",
            "task_title_placeholder": "Заголовок",
            "task_desc_placeholder": "Описание",
            "task_budget_placeholder": "Бюджет (например 50 000 ₸)",
            "task_category": "Категория",
            "task_deadline": "Срок",
            "task_new": "Новая задача",
            "task_post_failed": "Не удалось опубликовать задачу. Попробуй ещё раз.",
            "task_response_placeholder": "Чем можешь помочь?",
            "task_response_title": "Отклик",
            "task_response_failed": "Не удалось отправить отклик.",
            "chat_send_failed": "Не отправилось",
            "chat_mic_denied_title": "Нет доступа к микрофону",
            "chat_mic_denied_message": "Чтобы записывать голосовые, разреши X5 микрофон в Настройках iOS → X5.",
            "home_welcome_title": "Добро пожаловать в X5",
            "home_welcome_subtitle": "Маркетплейс для креаторов и клиентов. Используй вкладки внизу:",
            "home_welcome_hub": "Найди задачи от клиентов или опубликуй свою.",
            "home_welcome_chats": "Личные сообщения с клиентами и специалистами.",
            "home_welcome_courses": "Уроки от других креаторов — видео и тексты.",
            "home_welcome_profile": "Портфолио, баланс, настройки и Pro-подписка.",
            "chats_search_placeholder": "Поиск в чате",
            "chats_msg_copy": "Копировать",
            "chats_msg_pin": "Закрепить",
            "chats_msg_unpin": "Открепить",
            "chats_msg_delete_for_me": "Удалить у меня",
            "chats_msg_forward": "Переслать",
            "chats_pinned_label": "Закреплено",
            "chats_delete": "Удалить",
            "chats_archive_empty_title": "Архив пуст",
            "chats_archive_empty_sub": "Свайпни чат влево чтоб скрыть его в архив",
            "chats_empty_title": "Пока нет переписок",
            "chats_empty_sub": "Открой Hub и напиши кому-нибудь.",
            "chats_no_messages": "(нет сообщений)",
            "chats_task": "Задача:",
            "chats_message_placeholder": "Сообщение…",
            "chats_send": "Отправить",
            "chats_view_profile": "тапни, чтобы открыть профиль",
            "chats_loading": "Загружаем чаты…",

            // Paywall
            "paywall_title": "Раскрой потенциал",
            "paywall_desc": "Доступ ко всем AI-инструментам, премиум-курсам и безлимитным генерациям.",
            "paywall_active": "X5 Pro активна",
            "paywall_until": "До",
            "paywall_subscribe": "Подписаться",
            "paywall_loading": "Загружаем подписку…",
            "paywall_unavailable": "Подписка сейчас недоступна. Попробуйте позже.",
            "paywall_cancel_anytime": "Отменить можно в любой момент в настройках iOS",
            "paywall_privacy_link": "Политика конфиденциальности",
            "paywall_subscription_terms": "X5 Pro — автоматически продлеваемая ежемесячная подписка $9.99/мес. Оплата списывается с Apple ID при подтверждении покупки. Подписка продлевается автоматически, если не отменить её минимум за 24 часа до окончания периода. Управлять и отменить подписку можно в Настройках Apple ID. Любая неиспользованная часть бесплатного периода (если есть) сгорает при покупке подписки.",
            "paywall_restore": "Восстановить покупки",

            // Profile
            "profile_title": "Профиль",
            "profile_edit": "Редактировать профиль",
            "profile_credits": "Баланс",
            "profile_buy_credits": "Пополнить",
            "profile_upgrade": "Улучшить до Pro",
            "profile_get_verified": "Получить галочку",
            "profile_portfolio": "Портфолио",
            "profile_portfolio_empty": "Портфолио пустое",
            "profile_add_to_portfolio": "Добавить в портфолио",
            "profile_verified": "Проверенный",

            // Notifications
            "notif_title": "Уведомления",
            "notif_empty": "Нет уведомлений",

            // Verified
            "verified_title": "Получить галочку",
            "verified_subtitle": "Синяя ☑ рядом с твоим именем",
            "verified_benefit_1": "Приоритет в Hub — твои карточки выше",
            "verified_benefit_2": "Индикатор доверия для клиентов",
            "verified_benefit_3": "Знак того, что ты — настоящий специалист",
            "verified_subscribe": "Подписаться за 990 ₸/мес",
            "verified_active": "Галочка активна до",

            // App lock
            "app_lock_unlock_title": "Разблокируй X5",
            "app_lock_button": "Разблокировать",
            "app_lock_checking": "Проверяем…",
            "app_lock_unavailable": "Биометрия недоступна на устройстве. Отключи Face ID в настройках X5.",
            "app_lock_reason": "Доступ к X5",
            "app_lock_failed": "Не удалось разблокировать",
            "app_lock_passcode_fallback": "Введи код-пароль",

            // Notifications
            "notif_empty_desc": "Когда кто-то ответит на твою задачу, примет твоё предложение или напишет в чат — появится здесь.",

            // Hub report/block
            "hub_report_user": "Пожаловаться",
            "hub_block_user": "Заблокировать",
            "hub_block_author": "Заблокировать автора",
            "hub_block_user_title": "Заблокировать пользователя?",
            "hub_block_author_title": "Заблокировать автора?",
            "hub_block_user_message": "Контент этого пользователя больше не будет показываться.",
            "hub_block_author_message": "Задачи и сообщения этого автора больше не будут показываться.",
            "hub_open_profile": "Открыть профиль",

            // Hub task detail
            "hub_anonymous": "Анонимно",
            "hub_specialist": "Специалист",
            "hub_deadline": "Дедлайн",
            "hub_responses_label": "ОТКЛИКИ",
            "hub_no_responses": "Откликов пока нет.",
            "hub_author_notice": "Это твоя задача — отклики выше, можешь принять одного.",
            "hub_response_sent": "Твой отклик отправлен. Ждём, пока автор примет.",
            "hub_task_closed": "Задача закрыта для новых откликов.",
            "hub_respond_to_task": "Откликнуться",
            "hub_accepted": "ПРИНЯТ",

            // User profile
            "user_open": "Opening…",
            "user_send_message": "Написать сообщение",

            // Main view
            "main_target_length": "Целевая длина",
            "main_generate": "Сгенерировать",
            "main_short": "Коротко",
            "main_medium": "Средне",
            "main_long": "Длинно",

            // Profile / common
            "profile_title": "Профиль",

            // Onboarding
            "onb_title": "Расскажи о себе",
            "onb_subtitle": "Это поможет настроить опыт и то, что ты увидишь в Hub.",
            "onb_role_specialist": "Я специалист",
            "onb_role_specialist_sub": "Продаю свои навыки (маркетолог, дизайнер, разработчик, копирайтер и т.д.)",
            "onb_role_entrepreneur": "Я предприниматель",
            "onb_role_entrepreneur_sub": "Веду бизнес и хочу нанимать специалистов",
            "onb_pick_categories": "Выбери до 3 категорий",
            "onb_bio_label": "Короткое био (по желанию)",
            "onb_bio_placeholder": "напр. 7 лет в performance-маркетинге для SaaS",
            "onb_entrepreneur_note": "Ты сможешь публиковать задачи в Hub и сразу писать специалистам.",
            "onb_continue": "Продолжить",
            "onb_saving": "Сохраняем…",
            "onb_save_failed": "Не удалось сохранить роль.",

            // Paywall extra
            "paywall_title": "X5 Pro",
            "paywall_feat_credits": "1000 кредитов при подписке",
            "paywall_feat_tools": "Все ИИ-инструменты (фото, видео, lipsync, дизайн)",
            "paywall_feat_courses": "Полная библиотека курсов",
            "paywall_feat_hub": "Найм проверенных маркетологов в Hub",
            "paywall_feat_support": "Приоритетная поддержка",
            "paywall_terms_link": "Условия использования (EULA)",
            "paywall_welcome_pro": "Добро пожаловать в Pro!",
            "paywall_credits_added": "1000 кредитов начислено на твой баланс.",
            "paywall_continue": "Продолжить",

            // Courses extra
            "courses_create_btn": "Создать",

            // Common
            "common_anonymous": "Анонимно",

            // IAP errors
            "iap_invalid_url": "Не удалось сформировать ссылку покупки.",

            // Settings extra
            "settings_manage_subscription": "Управление подпиской",
        ],
        .en: [
            "btn_save": "Save",
            "btn_cancel": "Cancel",
            "btn_back": "Back",
            "btn_done": "Done",
            "btn_delete": "Delete",
            "btn_continue": "Continue",
            "btn_loading": "Loading…",
            "btn_retry": "Try again",
            "common_user": "User",
            "common_save": "Save",
            "common_post": "Post",
            "common_load_failed": "Could not load",
            "common_about": "About",
            "edit_specialist": "Specialist",
            "edit_show_in_hub": "Show in Hub",
            "edit_categories": "Categories",
            "edit_social": "Social links",
            "edit_about_section": "About",
            "courses_pro_chip": "Pro",
            "courses_draft": "DRAFT",
            "courses_unlock_pro": "Unlock with Pro",
            "courses_lessons_section": "LESSONS",
            "courses_free_preview": "FREE PREVIEW",
            "courses_lessons_word": "lessons",
            "brand_voice_title": "Brand voice",
            "brand_voice_sub": "Optional — personalises your captions. Stored only on this device.",
            "tool_in_dev": "In development — coming soon",
            "tool_notify_me": "Notify me when ready",
            "tool_will_let_you_know": "We will let you know",
            "brand_name_field": "Brand name",
            "brand_niche_field": "Niche (e.g. third-wave coffee)",
            "brand_audience_field": "Audience (e.g. urban professionals)",
            "brand_words_field": "Brand words (comma-separated)",
            "brand_reset": "Reset",
            "common_done": "Done",
            "tool_desc_default": "More details soon.",
            "tool_desc_photo": "Generate marketing-grade product and lifestyle photos from a text prompt. Adjust angle, lighting and style without a studio.",
            "tool_desc_video_gen": "AI video generation (Kling 3.0). Turn a still or a script into a short clip ready for Reels, TikTok and Shorts.",
            "tool_desc_outfit_swap": "Swap outfits on people in any photo while preserving body shape and lighting.",
            "tool_desc_lipsync": "Sync lip movement to any audio track. Voice-overs and dubbing for Reels and ads.",
            "tool_desc_design": "Brand banners, story tiles, ad sets and pitch decks generated to your brand guide.",
            "tool_desc_voice_tts": "Text-to-speech with emotion control. Multiple voices and languages for ads and tutorials.",
            "tool_desc_whatsapp_bot": "Auto-responder for incoming WhatsApp leads. Books, qualifies and routes 24/7.",
            "tool_desc_instagram": "Content plan generator. Get a 14-day Instagram schedule tuned to your niche and tone.",
            "tool_desc_video_creative": "Reels and TikTok scripts with hook → tension → CTA structure, ready to film.",
            "tool_desc_lawyer": "Generate vetted contracts, NDAs, service acts and proposals tailored to your business.",
            "tool_desc_academy": "Open the X5 Academy. Tap the Courses tab in the navigation.",
            "tool_desc_crm": "Lightweight CRM for solo founders and small agencies. Pipeline, deals, contacts.",
            "tool_desc_analytics": "Daily KPI digest from your channels: ad spend, ROAS, top creatives, conversion.",
            "tool_desc_captions": "Caption templates with platform-aware length. This one is live today — tap the card to open.",
            "tool_desc_ai_influencer": "Build a consistent virtual influencer character that stays on-model across photos and videos.",
            "tool_desc_edit_image": "Edit any photo with AI: face swap, relight, skin enhance, background change.",
            "tool_desc_vfx_library": "Cinematic transitions and VFX library. Drop a clip in, pick a style.",
            "courses_load_failed": "Could not load courses",
            "history_empty_title": "Nothing yet",
            "history_empty_sub": "Saved items will show up here.",
            "tool_status": "STATUS",
            "tool_coming_soon": "In development — coming soon",
            "tool_what_it_does": "WHAT IT WILL DO",
            "task_section": "Task",
            "task_budget_category": "Budget & category",
            "task_budget": "Budget",
            "task_your_message": "Your message",
            "task_response_footer": "When the author accepts your response, a private chat opens.",
            "task_send": "Send",
            "iap_signin_first": "Sign in first",

            "tab_home": "Home",
            "tab_courses": "Courses",
            "tab_chats": "Chats",
            "tab_hub": "Hub",
            "tab_profile": "Profile",

            "login_title": "Welcome to X5",
            "login_subtitle": "Marketing studio for creators.\nGenerate, learn, and hire — in one app.",
            "login_signin": "Sign in to X5",
            "login_signup": "Create your account",
            "login_continue_apple": "Continue with Apple",
            "login_continue_google": "Continue with Google",
            "login_continue_email": "Continue with Email",
            "login_email": "Email",
            "login_password": "Password",
            "login_create": "Create account",
            "login_have_account": "Already have an account? Sign in",
            "login_new_here": "New here? Create an account",
            "login_invalid": "Invalid email or password.",
            "login_already": "This email is already registered.",
            "login_password_short": "Password must be at least 6 characters.",

            "settings_title": "Settings",
            "settings_account": "Account",
            "settings_email": "Email",
            "settings_subscription": "Subscription",
            "settings_pro_active": "Pro · active",
            "settings_free": "Free",
            "settings_language": "Language",
            "settings_appearance": "Appearance",
            "settings_face_id": "Face ID",
            "settings_face_id_sub": "Protect app entry",
            "settings_public_profile": "Public profile",
            "settings_public_profile_sub": "Show me in Hub",
            "settings_notifications": "Notifications",
            "settings_notifications_sub": "Open system settings",
            "settings_clear_cache": "Clear cache",
            "settings_cache": "Cache",
            "settings_cache_sub": "See what's stored and clear it",
            "settings_promo": "Promo notifications",
            "settings_promo_sub": "Light reminders every 5 minutes",
            "cache_title": "Cache",
            "cache_total": "Total on disk",
            "cache_pick": "What's stored",
            "cache_pick_hint": "Pick categories to remove. Leave empty to wipe everything.",
            "cache_empty": "Empty",
            "cache_clear_all": "Clear all cache",
            "cache_clear_selected": "Delete selected",
            "cache_cat_avatars": "Avatars",
            "cache_cat_courses": "Course covers",
            "cache_cat_portfolio": "Portfolio",
            "cache_cat_chat": "Chat media",
            "cache_cat_other": "Other",
            "settings_signout": "Sign out",
            "settings_legal": "Legal",
            "settings_privacy": "Privacy Policy",
            "settings_terms": "Terms of Service",
            "settings_support": "Contact support",
            "settings_danger": "Danger zone",
            "settings_delete": "Delete account",
            "settings_delete_footer": "This will permanently delete your account and all associated data. This action cannot be undone.",
            "settings_delete_confirm": "Delete account?",
            "settings_delete_confirm_msg": "This will permanently remove your account and all associated data. You will not be able to recover it.",
            "settings_delete_sure": "Are you absolutely sure?",
            "settings_delete_sure_msg": "Once deleted, your account cannot be recovered.",
            "settings_delete_forever": "Delete forever",
            "settings_deleting": "Deleting…",
            "settings_delete_failed": "Delete failed",
            "settings_cache_cleared": "Cache cleared",
            "settings_choose_language": "App language",

            "hub_title": "Hub",
            "hub_specialists": "Specialists",
            "hub_tasks": "Tasks",
            "hub_post": "Post",
            "hub_become_specialist": "Become a specialist",
            "hub_no_specialists": "No specialists yet",
            "hub_no_specialists_sub": "Check back soon — Hub is filling up.",
            "hub_no_tasks": "No open tasks",
            "hub_no_tasks_sub": "When entrepreneurs post tasks, they'll appear here.",
            "hub_send_message": "Send message",
            "hub_all": "All",

            "chats_title": "Chats",
            "chats_archive": "Archive",
            "chats_unarchive": "Unarchive",
            "chats_mute": "Mute",
            "chats_unmute": "Unmute",
            "chats_pin": "Pin",
            "chats_unpin": "Unpin",
            "chat_recording_hint": "Recording… release to send",
            "chat_voice_message": "Voice message",
            "chat_block_title": "Block this user?",
            "chat_block_confirm": "Block",
            "chat_block_message": "Messages from this user will no longer be shown.",
            "chat_open_profile": "Open profile",
            "chat_report_user": "Report",
            "chat_block_user": "Block",
            "common_cancel": "Cancel",
            "edit_hub_footer": "Toggle \"Show in Hub\" to make your profile visible to clients who can then start a chat.",
            "edit_public_profile": "Public profile for clients",
            "edit_name_placeholder": "Name",
            "edit_nickname_placeholder": "Username (a-z 0-9 _)",
            "edit_bio_placeholder": "A short bio",
            "edit_social_footer": "Clients will see these links on your Hub profile.",
            "edit_profile": "Profile",
            "settings_language_footer": "App language follows the iPhone language. To change it — iOS Settings → X5 → Language.",
            "settings_lang_from_system": "from system",
            "portfolio_title": "Portfolio",
            "portfolio_empty_self": "Upload your work",
            "portfolio_empty_other": "Portfolio is empty",
            "portfolio_delete_title": "Remove from portfolio?",
            "portfolio_pick_photo": "Pick a photo",
            "portfolio_description_section": "Description",
            "portfolio_title_optional": "Title (optional)",
            "portfolio_desc_optional": "Case / description (optional)",
            "portfolio_add_title": "Add to portfolio",
            "portfolio_save_failed": "Could not save. Try again.",
            "common_add": "Add",
            "common_delete": "Delete",
            "profile_become_specialist": "Become a specialist",
            "profile_become_specialist_sub": "Turn on a public profile — clients will find you in Hub and start a chat",
            "profile_get_verified": "Get verified",
            "profile_get_verified_sub": "Blue ☑ next to your name — more trust and priority in Hub",
            "hub_chat_failed": "Chat could not be opened",
            "hub_chat_failed_retry": "Could not open chat. Try again.",
            "verified_activated_message": "The blue check is now next to your name. %d credits were deducted.",
            "verified_cost_label": "%d credits / 30 days",
            "verified_balance": "Your balance: %d",
            "verified_activating": "Activating…",
            "verified_activate_for": "Activate for %d credits",
            "verified_buy_pro_to_get_credits": "Buy Pro and get credits",
            "verified_pro_credits_hint": "Pro = +1000 credits instantly",
            "verified_activate_failed": "Could not activate. Try again later.",
            "iap_not_enough_credits": "Not enough credits: need %d, you have %d. Buy Pro — you will get 1000 credits.",
            "task_title_placeholder": "Title",
            "task_desc_placeholder": "Description",
            "task_budget_placeholder": "Budget (e.g. 50 000 ₸)",
            "task_category": "Category",
            "task_deadline": "Deadline",
            "task_new": "New task",
            "task_post_failed": "Could not post the task. Please try again.",
            "task_response_placeholder": "How can you help?",
            "task_response_title": "Response",
            "task_response_failed": "Could not send your response.",
            "chat_send_failed": "Send failed",
            "chat_mic_denied_title": "Microphone access denied",
            "chat_mic_denied_message": "To record voice messages, allow X5 microphone access in iOS Settings → X5.",
            "home_welcome_title": "Welcome to X5",
            "home_welcome_subtitle": "A marketplace for creators and clients. Use the tabs below:",
            "home_welcome_hub": "Find tasks from clients or post your own.",
            "home_welcome_chats": "Direct messages with clients and specialists.",
            "home_welcome_courses": "Lessons from other creators — video and reading.",
            "home_welcome_profile": "Portfolio, credits, settings and Pro subscription.",
            "chats_search_placeholder": "Search in chat",
            "chats_msg_copy": "Copy",
            "chats_msg_pin": "Pin",
            "chats_msg_unpin": "Unpin",
            "chats_msg_delete_for_me": "Delete for me",
            "chats_msg_forward": "Forward",
            "chats_pinned_label": "Pinned",
            "chats_delete": "Delete",
            "chats_archive_empty_title": "Archive is empty",
            "chats_archive_empty_sub": "Swipe a chat left to move it here",
            "chats_empty_title": "No conversations yet",
            "chats_empty_sub": "Open Hub and reach out to someone.",
            "chats_no_messages": "(no messages)",
            "chats_task": "Task:",
            "chats_message_placeholder": "Message…",
            "chats_send": "Send",
            "chats_view_profile": "tap to view profile",
            "chats_loading": "Loading chats…",

            "paywall_title": "Unlock the potential",
            "paywall_desc": "Access all AI tools, premium courses, and unlimited generations.",
            "paywall_active": "X5 Pro Active",
            "paywall_until": "Until",
            "paywall_subscribe": "Subscribe",
            "paywall_loading": "Loading subscription…",
            "paywall_unavailable": "Subscription is not available right now. Please try again later.",
            "paywall_cancel_anytime": "Cancel anytime in iOS Settings",
            "paywall_privacy_link": "Privacy Policy",
            "paywall_subscription_terms": "X5 Pro is an auto-renewing monthly subscription at $9.99/month. Payment will be charged to your Apple ID at purchase confirmation. Subscription auto-renews unless cancelled at least 24 hours before the end of the current period. Manage or cancel anytime in your Apple ID settings. Any unused portion of a free trial period, if offered, will be forfeited when you purchase a subscription.",
            "paywall_restore": "Restore purchases",

            "profile_title": "Profile",
            "profile_edit": "Edit profile",
            "profile_credits": "Credits",
            "profile_buy_credits": "Top up",
            "profile_upgrade": "Upgrade to Pro",
            "profile_get_verified": "Get verified",
            "profile_portfolio": "Portfolio",
            "profile_portfolio_empty": "Portfolio is empty",
            "profile_add_to_portfolio": "Add to portfolio",
            "profile_verified": "Verified",

            "notif_title": "Notifications",
            "notif_empty": "No notifications",

            "verified_title": "Get verified",
            "verified_subtitle": "A blue ☑ next to your name",
            "verified_benefit_1": "Priority in Hub — your cards rank higher",
            "verified_benefit_2": "Trust signal for clients",
            "verified_benefit_3": "Proof that you're a real specialist",
            "verified_subscribe": "Subscribe for $1.99/mo",
            "verified_active": "Verified until",

            // App lock
            "app_lock_unlock_title": "Unlock X5",
            "app_lock_button": "Unlock",
            "app_lock_checking": "Checking…",
            "app_lock_unavailable": "Biometry unavailable on this device. Disable Face ID in X5 settings.",
            "app_lock_reason": "Access X5",
            "app_lock_failed": "Could not unlock",
            "app_lock_passcode_fallback": "Enter passcode",

            // Notifications
            "notif_empty_desc": "When someone replies to your task, accepts your offer or sends a chat message, it will appear here.",

            // Hub report/block
            "hub_report_user": "Report",
            "hub_block_user": "Block",
            "hub_block_author": "Block author",
            "hub_block_user_title": "Block user?",
            "hub_block_author_title": "Block author?",
            "hub_block_user_message": "This user's content will no longer be shown.",
            "hub_block_author_message": "Tasks and messages from this author will no longer be shown.",
            "hub_open_profile": "Open profile",

            // Hub task detail
            "hub_anonymous": "Anonymous",
            "hub_specialist": "Specialist",
            "hub_deadline": "Deadline",
            "hub_responses_label": "RESPONSES",
            "hub_no_responses": "No responses yet.",
            "hub_author_notice": "This is your task — you'll see responses above and can accept one.",
            "hub_response_sent": "Your response is sent. Wait for the author to accept it.",
            "hub_task_closed": "This task is closed for new responses.",
            "hub_respond_to_task": "Respond to task",
            "hub_accepted": "ACCEPTED",

            // User profile
            "user_open": "Opening…",
            "user_send_message": "Send message",

            // Main view
            "main_target_length": "Target length",
            "main_generate": "Generate",
            "main_short": "Short",
            "main_medium": "Medium",
            "main_long": "Long",

            // Profile / common
            "profile_title": "Profile",

            // Onboarding
            "onb_title": "Tell us who you are",
            "onb_subtitle": "This helps us tailor your experience and what you see in Hub.",
            "onb_role_specialist": "I'm a specialist",
            "onb_role_specialist_sub": "I sell my skills (marketer, designer, dev, copywriter, etc.)",
            "onb_role_entrepreneur": "I'm an entrepreneur",
            "onb_role_entrepreneur_sub": "I run a business and want to hire specialists",
            "onb_pick_categories": "Pick up to 3 categories",
            "onb_bio_label": "Short bio (optional)",
            "onb_bio_placeholder": "e.g. 7y in performance marketing for SaaS",
            "onb_entrepreneur_note": "You'll be able to post tasks in Hub and chat with specialists right after.",
            "onb_continue": "Continue",
            "onb_saving": "Saving…",
            "onb_save_failed": "Could not save your role.",

            // Paywall extra
            "paywall_title": "X5 Pro",
            "paywall_feat_credits": "1000 credits added on subscribe",
            "paywall_feat_tools": "All AI tools (image, video, lipsync, design)",
            "paywall_feat_courses": "Full courses library",
            "paywall_feat_hub": "Hire vetted marketers in Hub",
            "paywall_feat_support": "Priority support",
            "paywall_terms_link": "Terms of Use (EULA)",
            "paywall_welcome_pro": "Welcome to Pro!",
            "paywall_credits_added": "1000 credits have been added to your balance.",
            "paywall_continue": "Continue",

            // Courses extra
            "courses_create_btn": "Create",

            // Common
            "common_anonymous": "Anonymous",

            // IAP errors
            "iap_invalid_url": "Could not build purchase URL.",

            // Settings extra
            "settings_manage_subscription": "Manage subscription",
        ],
        .kk: [
            "btn_save": "Сақтау",
            "btn_cancel": "Болдырмау",
            "btn_back": "Артқа",
            "btn_done": "Дайын",
            "btn_delete": "Жою",
            "btn_continue": "Жалғастыру",
            "btn_loading": "Жүктелуде…",
            "btn_retry": "Қайта көру",
            "common_user": "Пайдаланушы",
            "common_save": "Сақтау",
            "common_post": "Жариялау",
            "common_load_failed": "Жүктеу мүмкін болмады",
            "common_about": "Өзім туралы",
            "edit_specialist": "Маман",
            "edit_show_in_hub": "Hub-та көрсету",
            "edit_categories": "Санаттар",
            "edit_social": "Әлеуметтік желілер",
            "edit_about_section": "Өзім туралы",
            "courses_pro_chip": "Pro",
            "courses_draft": "ҚАРАЛАМА",
            "courses_unlock_pro": "Pro-мен ашу",
            "courses_lessons_section": "САБАҚТАР",
            "courses_free_preview": "ТЕГІН",
            "courses_lessons_word": "сабақ",
            "brand_voice_title": "Бренд дауысы",
            "brand_voice_sub": "Қалауыңша — мәтіндер сенің стиліңде шығады. Тек осы құрылғыда сақталады.",
            "tool_in_dev": "Әзірленуде — жақында",
            "tool_notify_me": "Дайын болғанда хабарла",
            "tool_will_let_you_know": "Дайын болғанда хабарлаймыз",
            "brand_name_field": "Бренд атауы",
            "brand_niche_field": "Ниша (мысалы, спешелти-кофе)",
            "brand_audience_field": "Аудитория (мысалы, қалалық кәсіпқойлар)",
            "brand_words_field": "Бренд сөздері (үтір арқылы)",
            "brand_reset": "Қалпына келтіру",
            "common_done": "Дайын",
            "tool_desc_default": "Толық ақпарат жақында.",
            "tool_desc_photo": "Мәтін бойынша маркетингтік өнім және lifestyle фотолар жасайды. Бұрышты, жарық пен стильді студиясыз баптайсың.",
            "tool_desc_video_gen": "ИИ-видео (Kling 3.0). Кадр немесе сценарий — Reels, TikTok және Shorts үшін қысқа ролик.",
            "tool_desc_outfit_swap": "Кез келген фотодағы адамның киімін ауыстыр — пішін мен жарық сақталады.",
            "tool_desc_lipsync": "Кез келген аудиоға ерін қимылын синхронда. Reels пен жарнамаға дубляж.",
            "tool_desc_design": "Сенің бренд-стиліңмен баннер, сторис, жарнама және питч-дек жасайды.",
            "tool_desc_voice_tts": "Эмоциясы бар мәтіннен сөйлеуге. Жарнама мен оқуға арналған әртүрлі дауыс пен тіл.",
            "tool_desc_whatsapp_bot": "WhatsApp лидтеріне авто-жауапшы. 24/7 жазады, квалификациялайды, бағыттайды.",
            "tool_desc_instagram": "14 күнге Instagram контент-жоспары — сенің нишаң мен үніңе сай.",
            "tool_desc_video_creative": "Reels және TikTok сценарийлері: hook → tension → CTA, түсіруге дайын.",
            "tool_desc_lawyer": "Сенің бизнесіңе бейімделген келісімшарт, NDA, акт және ұсыныстар.",
            "tool_desc_academy": "X5 Academy ашу. Төмендегі «Курстар» бөлімін бас.",
            "tool_desc_crm": "Соло-фаундерлер мен шағын агенттіктерге арналған жеңіл CRM. Шұңғыма, мәмілелер, контактілер.",
            "tool_desc_analytics": "Күн сайынғы KPI-дайджест: жарнама шығыны, ROAS, үздік креативтер, конверсия.",
            "tool_desc_captions": "Платформаға бейім ұзындықпен подпись шаблондары. Бұл құрал қазір жұмыс істейді — картаны бас.",
            "tool_desc_ai_influencer": "Фото мен видеода біркелкі қалатын виртуал инфлюенсер құрастыр.",
            "tool_desc_edit_image": "ИИ-мен фотоны өңде: бет ауыстыру, жарық, тері ретушы, фон ауыстыру.",
            "tool_desc_vfx_library": "Кинематографиялық өтпелі эффекттер мен VFX кітапханасы. Клип қос — стильді таңда.",
            "courses_load_failed": "Курстар жүктелмеді",
            "history_empty_title": "Әлі бос",
            "history_empty_sub": "Сақталған заттар осында пайда болады.",
            "tool_status": "МӘРТЕБЕ",
            "tool_coming_soon": "Әзірленуде — жақында",
            "tool_what_it_does": "НЕ ІСТЕЙДІ",
            "task_section": "Тапсырма",
            "task_budget_category": "Бюджет және санат",
            "task_budget": "Бюджет",
            "task_your_message": "Хабарламаң",
            "task_response_footer": "Автор жауапты қабылдағанда жеке чат ашылады.",
            "task_send": "Жіберу",
            "iap_signin_first": "Алдымен кіріңіз",

            "tab_home": "Басты",
            "tab_courses": "Курстар",
            "tab_chats": "Чаттар",
            "tab_hub": "Hub",
            "tab_profile": "Профиль",

            "login_title": "X5-ке қош келдің",
            "login_subtitle": "Креаторларға арналған маркетинг студиясы.\nГенерациялау, оқу, жалдау — бір қосымшада.",
            "login_signin": "X5-ке кіру",
            "login_signup": "Аккаунт құру",
            "login_continue_apple": "Apple арқылы кіру",
            "login_continue_google": "Google арқылы кіру",
            "login_continue_email": "Email арқылы кіру",
            "login_email": "Email",
            "login_password": "Құпиясөз",
            "login_create": "Аккаунт құру",
            "login_have_account": "Аккаунтың бар ма? Кіру",
            "login_new_here": "Жаңасың ба? Аккаунт құр",
            "login_invalid": "Қате email немесе құпиясөз.",
            "login_already": "Бұл email тіркелген.",
            "login_password_short": "Құпиясөз кемінде 6 таңба болуы керек.",

            "settings_title": "Баптаулар",
            "settings_account": "Аккаунт",
            "settings_email": "Email",
            "settings_subscription": "Жазылым",
            "settings_pro_active": "Pro · белсенді",
            "settings_free": "Тегін",
            "settings_language": "Тіл",
            "settings_appearance": "Көрініс",
            "settings_face_id": "Face ID",
            "settings_face_id_sub": "Қосымшаны қорғау",
            "settings_public_profile": "Публикалық профиль",
            "settings_public_profile_sub": "Hub-та көрсетілсін",
            "settings_notifications": "Хабарламалар",
            "settings_notifications_sub": "Жүйе баптауларын ашу",
            "settings_clear_cache": "Кэшті тазалау",
            "settings_cache": "Кэш",
            "settings_cache_sub": "Қанша орын алады және не өшіру",
            "settings_promo": "Промо хабарламалары",
            "settings_promo_sub": "Әр 5 минут сайын жеңіл еске салулар",
            "cache_title": "Кэш",
            "cache_total": "Дискіде барлығы",
            "cache_pick": "Не сақталған",
            "cache_pick_hint": "Өшіретін санаттарды таңда. Таңдалмаса — бәрін тазалайды.",
            "cache_empty": "Бос",
            "cache_clear_all": "Барлық кэшті тазалау",
            "cache_clear_selected": "Таңдалғанды өшіру",
            "cache_cat_avatars": "Аватарлар",
            "cache_cat_courses": "Курс мұқабалары",
            "cache_cat_portfolio": "Портфолио",
            "cache_cat_chat": "Чат медиасы",
            "cache_cat_other": "Басқа",
            "settings_signout": "Шығу",
            "settings_legal": "Құжаттар",
            "settings_privacy": "Құпиялылық саясаты",
            "settings_terms": "Қызмет шарттары",
            "settings_support": "Қолдауға хабарласу",
            "settings_danger": "Қауіпті аймақ",
            "settings_delete": "Аккаунтты жою",
            "settings_delete_footer": "Аккаунт пен барлық деректер біржола өшіріледі. Бұл әрекетті болдырмау мүмкін емес.",
            "settings_delete_confirm": "Аккаунтты жою керек пе?",
            "settings_delete_confirm_msg": "Бұл әрекет қайтымсыз. Профиль, тарих, кредиттер, чаттар, курстар — барлығы жойылады.",
            "settings_delete_sure": "Шынымен сенімдісің бе?",
            "settings_delete_sure_msg": "Жойылғаннан кейін аккаунтты қалпына келтіруге болмайды.",
            "settings_delete_forever": "Біржола жою",
            "settings_deleting": "Жойылуда…",
            "settings_delete_failed": "Жою сәтсіз",
            "settings_cache_cleared": "Кэш тазаланды",
            "settings_choose_language": "Қосымша тілі",

            "hub_title": "Hub",
            "hub_specialists": "Мамандар",
            "hub_tasks": "Тапсырмалар",
            "hub_post": "Жариялау",
            "hub_become_specialist": "Маман болу",
            "hub_no_specialists": "Әзірге маман жоқ",
            "hub_no_specialists_sub": "Кейінірек қара — Hub толып жатыр.",
            "hub_no_tasks": "Ашық тапсырма жоқ",
            "hub_no_tasks_sub": "Кәсіпкерлер тапсырма жариялағанда — осында пайда болады.",
            "hub_send_message": "Хабарлама жазу",
            "hub_all": "Барлығы",

            "chats_title": "Чаттар",
            "chats_archive": "Мұрағат",
            "chats_unarchive": "Мұрағаттан",
            "chats_mute": "Дыбыссыз",
            "chats_unmute": "Дыбыспен",
            "chats_pin": "Бекіту",
            "chats_unpin": "Босату",
            "chat_recording_hint": "Жазу… жіберу үшін босат",
            "chat_voice_message": "Дауыс",
            "chat_block_title": "Бұл пайдаланушыны бұғаттау?",
            "chat_block_confirm": "Бұғаттау",
            "chat_block_message": "Бұл пайдаланушының хабарламалары енді көрсетілмейді.",
            "chat_open_profile": "Профильді ашу",
            "chat_report_user": "Шағымдану",
            "chat_block_user": "Бұғаттау",
            "common_cancel": "Болдырмау",
            "edit_hub_footer": "«Hub-та көрсету» қосыңыз — профиліңіз Hub-та пайда болады, клиенттер чат жаза алады.",
            "edit_public_profile": "Клиенттерге арналған ашық профиль",
            "edit_name_placeholder": "Аты",
            "edit_nickname_placeholder": "Никнейм (a-z 0-9 _)",
            "edit_bio_placeholder": "Өзің туралы қысқаша",
            "edit_social_footer": "Бұл сілтемелерді клиенттер сіздің Hub профиліңізде көреді.",
            "edit_profile": "Профиль",
            "settings_language_footer": "Қолданба тілі iPhone тілінен алынады. Өзгерту үшін — iOS параметрлері → X5 → Тіл.",
            "settings_lang_from_system": "жүйеден",
            "portfolio_title": "Портфолио",
            "portfolio_empty_self": "Жұмыстарыңды жүкте",
            "portfolio_empty_other": "Портфолио бос",
            "portfolio_delete_title": "Портфолиодан жою?",
            "portfolio_pick_photo": "Фото таңда",
            "portfolio_description_section": "Сипаттама",
            "portfolio_title_optional": "Атауы (қалауы бойынша)",
            "portfolio_desc_optional": "Кейс / сипаттама (қалауы бойынша)",
            "portfolio_add_title": "Портфолиоға қосу",
            "portfolio_save_failed": "Сақталмады. Қайталап көр.",
            "common_add": "Қосу",
            "common_delete": "Жою",
            "profile_become_specialist": "Маман болу",
            "profile_become_specialist_sub": "Ашық профильді қос — клиенттер Hub-та сені табады және чат жазады",
            "profile_get_verified": "Растау белгісін алу",
            "profile_get_verified_sub": "Атының жанындағы көк ☑ — сенімділік пен Hub-та басымдық",
            "hub_chat_failed": "Чат ашылмады",
            "hub_chat_failed_retry": "Чатты ашу мүмкін болмады. Қайталап көр.",
            "verified_activated_message": "Атының жанында көк белгі. %d кредит шегерілді.",
            "verified_cost_label": "%d кредит / 30 күн",
            "verified_balance": "Балансың: %d",
            "verified_activating": "Шегеру…",
            "verified_activate_for": "%d кредитке белсендіру",
            "verified_buy_pro_to_get_credits": "Pro сатып ал және кредиттер ал",
            "verified_pro_credits_hint": "Pro = +1000 кредит бірден",
            "verified_activate_failed": "Белсендіру мүмкін болмады. Кейінірек қайталап көр.",
            "iap_not_enough_credits": "Кредит жетпейді: %d керек, сенде %d. Pro сатып ал — 1000 кредит аласың.",
            "task_title_placeholder": "Тақырыбы",
            "task_desc_placeholder": "Сипаттама",
            "task_budget_placeholder": "Бюджет (мысалы 50 000 ₸)",
            "task_category": "Санат",
            "task_deadline": "Мерзімі",
            "task_new": "Жаңа тапсырма",
            "task_post_failed": "Тапсырманы жариялау мүмкін болмады. Қайталап көр.",
            "task_response_placeholder": "Қалай көмектесе аласың?",
            "task_response_title": "Жауап",
            "task_response_failed": "Жауап жіберілмеді.",
            "chat_send_failed": "Жіберілмеді",
            "chat_mic_denied_title": "Микрофонға қол жетімсіз",
            "chat_mic_denied_message": "Дауыстық хабар жазу үшін iOS параметрлерінде X5-ке микрофонды рұқсат ет.",
            "home_welcome_title": "X5-ке қош келдің",
            "home_welcome_subtitle": "Креаторлар мен клиенттерге арналған маркетплейс. Төмендегі қойындыларды қолдан:",
            "home_welcome_hub": "Клиенттердің тапсырмаларын тап немесе өзіңдікін жариялы.",
            "home_welcome_chats": "Клиенттер және мамандармен жеке хабарлар.",
            "home_welcome_courses": "Басқа креаторлардың сабақтары — видео мен мәтін.",
            "home_welcome_profile": "Портфолио, баланс, баптаулар және Pro-жазылым.",
            "chats_search_placeholder": "Чатта іздеу",
            "chats_msg_copy": "Көшіру",
            "chats_msg_pin": "Бекіту",
            "chats_msg_unpin": "Босату",
            "chats_msg_delete_for_me": "Менде өшіру",
            "chats_msg_forward": "Жіберу",
            "chats_pinned_label": "Бекітілген",
            "chats_delete": "Жою",
            "chats_archive_empty_title": "Мұрағат бос",
            "chats_archive_empty_sub": "Чатты солға сырғыт - мұрағатқа түседі",
            "chats_empty_title": "Әзірге чат жоқ",
            "chats_empty_sub": "Hub-ты ашып, біреуге жаз.",
            "chats_no_messages": "(хабарлама жоқ)",
            "chats_task": "Тапсырма:",
            "chats_message_placeholder": "Хабарлама…",
            "chats_send": "Жіберу",
            "chats_view_profile": "профильді ашу үшін басыңыз",
            "chats_loading": "Чаттар жүктелуде…",

            "paywall_title": "Әлеуетті аш",
            "paywall_desc": "Барлық AI құралдарға, премиум курстарға және шексіз генерацияларға қол жетімділік.",
            "paywall_active": "X5 Pro белсенді",
            "paywall_until": "Дейін",
            "paywall_subscribe": "Жазылу",
            "paywall_loading": "Жазылым жүктелуде…",
            "paywall_unavailable": "Жазылым қазір қол жетімсіз. Кейінірек көріңіз.",
            "paywall_cancel_anytime": "Кез келген уақытта iOS баптауларынан тоқтатуға болады",
            "paywall_privacy_link": "Құпиялылық саясаты",
            "paywall_subscription_terms": "X5 Pro — автоматты жаңартылатын айлық жазылым $9.99/ай. Төлем сатып алуды растаған кезде Apple ID-ге жазылады. Ағымдағы кезеңнің аяқталуына кемінде 24 сағат қалғанда тоқтатылмаса, жазылым автоматты түрде жаңарады. Жазылымды Apple ID параметрлерінде басқаруға және тоқтатуға болады.",
            "paywall_restore": "Сатып алуларды қалпына келтіру",

            "profile_title": "Профиль",
            "profile_edit": "Профильді өзгерту",
            "profile_credits": "Баланс",
            "profile_buy_credits": "Толтыру",
            "profile_upgrade": "Pro-ға жаңарту",
            "profile_get_verified": "Растау белгісін алу",
            "profile_portfolio": "Портфолио",
            "profile_portfolio_empty": "Портфолио бос",
            "profile_add_to_portfolio": "Портфолиоға қосу",
            "profile_verified": "Расталған",

            "notif_title": "Хабарламалар",
            "notif_empty": "Хабарлама жоқ",

            "verified_title": "Растау белгісін алу",
            "verified_subtitle": "Атың жанындағы көк ☑",
            "verified_benefit_1": "Hub-та басымдылық — карточкаң жоғары тұрады",
            "verified_benefit_2": "Клиенттер үшін сенім белгісі",
            "verified_benefit_3": "Сен нағыз маман екеніңнің дәлелі",
            "verified_subscribe": "990 ₸/айға жазылу",
            "verified_active": "Дейін расталған",

            // App lock
            "app_lock_unlock_title": "X5-ті ашу",
            "app_lock_button": "Ашу",
            "app_lock_checking": "Тексеру…",
            "app_lock_unavailable": "Биометрия қол жетімсіз. X5 параметрлерінде Face ID өшіріңіз.",
            "app_lock_reason": "X5-ке кіру",
            "app_lock_failed": "Аша алмадық",
            "app_lock_passcode_fallback": "Құпиясөзді еңгіз",

            // Notifications
            "notif_empty_desc": "Біреу тапсырмаңа жауап берсе, ұсынысыңды қабылдаса немесе чатқа жазса — осында пайда болады.",

            // Hub report/block
            "hub_report_user": "Шағымдану",
            "hub_block_user": "Блоктау",
            "hub_block_author": "Авторды блоктау",
            "hub_block_user_title": "Қолданушыны блоктау?",
            "hub_block_author_title": "Авторды блоктау?",
            "hub_block_user_message": "Бұл қолданушының контенті бұдан былай көрсетілмейді.",
            "hub_block_author_message": "Бұл автордың тапсырмалары мен хабарлары бұдан былай көрсетілмейді.",
            "hub_open_profile": "Профильді ашу",

            // Hub task detail
            "hub_anonymous": "Анонимді",
            "hub_specialist": "Маман",
            "hub_deadline": "Мерзімі",
            "hub_responses_label": "ЖАУАПТАР",
            "hub_no_responses": "Әлі жауап жоқ.",
            "hub_author_notice": "Бұл — сенің тапсырмаң. Жауаптар жоғарыда, біреуін қабылдай аласың.",
            "hub_response_sent": "Жауабың жіберілді. Автор қабылдағанша күт.",
            "hub_task_closed": "Бұл тапсырма жаңа жауаптар үшін жабық.",
            "hub_respond_to_task": "Жауап беру",
            "hub_accepted": "ҚАБЫЛДАНДЫ",

            // User profile
            "user_open": "Ашу…",
            "user_send_message": "Хабарлама жазу",

            // Main view
            "main_target_length": "Қажетті ұзындық",
            "main_generate": "Генерациялау",
            "main_short": "Қысқа",
            "main_medium": "Орташа",
            "main_long": "Ұзақ",

            // Profile / common
            "profile_title": "Профиль",

            // Onboarding
            "onb_title": "Өзің туралы айтып бер",
            "onb_subtitle": "Бұл тәжірибеңді және Hub-та көретін нәрсені баптауға көмектеседі.",
            "onb_role_specialist": "Мен маманмын",
            "onb_role_specialist_sub": "Дағдыларымды сатамын (маркетолог, дизайнер, әзірлеуші, копирайтер және т.б.)",
            "onb_role_entrepreneur": "Мен кәсіпкермін",
            "onb_role_entrepreneur_sub": "Бизнес жүргіземін, мамандарды жалдағым келеді",
            "onb_pick_categories": "3-тен аспайтын санат таңда",
            "onb_bio_label": "Қысқа био (қалауыңша)",
            "onb_bio_placeholder": "мысалы, SaaS-ке 7 жыл performance-маркетинг",
            "onb_entrepreneur_note": "Hub-та тапсырмалар жариялап, мамандармен бірден чатта сөйлесе аласың.",
            "onb_continue": "Жалғастыру",
            "onb_saving": "Сақтау…",
            "onb_save_failed": "Рөлді сақтау сәтсіз.",

            // Paywall extra
            "paywall_title": "X5 Pro",
            "paywall_feat_credits": "Жазылған кезде 1000 кредит қосылады",
            "paywall_feat_tools": "Барлық ИИ-құралдар (фото, видео, lipsync, дизайн)",
            "paywall_feat_courses": "Курстар кітапханасы толық",
            "paywall_feat_hub": "Hub-та расталған маркетологтарды жалдау",
            "paywall_feat_support": "Басым қолдау",
            "paywall_terms_link": "Қолдану шарттары (EULA)",
            "paywall_welcome_pro": "Pro-ға қош келдің!",
            "paywall_credits_added": "Балансыңа 1000 кредит қосылды.",
            "paywall_continue": "Жалғастыру",

            // Courses extra
            "courses_create_btn": "Жасау",

            // Common
            "common_anonymous": "Анонимді",

            // IAP errors
            "iap_invalid_url": "Сатып алу сілтемесін жасай алмадық.",

            // Settings extra
            "settings_manage_subscription": "Жазылымды басқару",
        ]
    ]
}
